import { AppStore } from '../store/AppStore';
import type { ConfigKey, PluginConfig } from '../types';

// ============================================================================
// Config
// ============================================================================

/**
 * Convenience wrapper for AppStore.getConfig / AppStore.setConfig.
 */
export const Config = {
    get<K extends ConfigKey>(key: K): PluginConfig[K] {
        return AppStore.getConfig(key);
    },
    set<K extends ConfigKey>(key: K, value: PluginConfig[K]): void {
        AppStore.setConfig(key, value);
    },
};

// ============================================================================
// Internationalization
// ============================================================================

type SupportedLang = 'en' | 'zh' | 'ja';
type I18nData = Record<string, Record<string, string>>;

const i18nData: I18nData = {
    en: {
        // Settings - Radio
        radioMode: 'Radio Mode',
        off: 'OFF',
        on: 'ON',
        radioStatusIdle: 'Idle',
        radioStatusStarting: 'Starting playback...',
        radioStatusLoading: 'Loading work...',
        radioStatusSkipping: 'Skipping to next work...',
        radioStatusPlaying: 'Playing',
        playAll: 'Play Entire Work',
        playAllSub: 'Play all tracks in queue before advancing to next work',
        radioFlatTracks: 'Track Pool: All Folders',
        radioFlatTracksSub: 'Use all audio tracks across folders instead of only one selected folder',
        trackPoolAllFolders: 'Track Pool: All Folders',
        trackPoolAllFoldersSub: 'Build queue from all audio in the work tree. With Play Entire Work off, one track is selected from this pool.',
        folderPoolSettings: 'Folder & Track Pool Settings',
        shuffle: 'Shuffle',
        shuffleSub: 'Randomize playback order',
        loopPlaylist: 'Loop',
        loopPlaylistSub: 'Restart playlist from the beginning when it ends',
        prefFormat: 'Preferred Format',
        prefFormatSub: 'e.g. wav, mp3',
        sePref: 'SE Preference',
        sePrefSub: 'Prefer folders with sound effects',
        bgmPref: 'BGM Preference',
        bgmPrefSub: 'Prefer folders with background music',
        primaryLang: 'Primary Language',
        primaryLangSub: 'Language code for main subtitle line (e.g. ja, en)',
        targetLang: 'Secondary Language',
        targetLangSub: 'Language code for secondary subtitles (e.g. en, es, fr)',
        liveCaptionTitle: 'Pro Tip: Live Caption',
        liveCaptionMsg: 'Try enabling system Live Caption for better accuracy!',
        prevLine: 'Previous Line',
        nextLine: 'Next Line',
        toggleJP: 'Toggle Japanese',
        radioSettings: 'Radio Settings',
        playlistSettings: 'Playlist Settings',
        autoProgress: 'Track Status',
        autoProgressSub: 'Automatically update work statuses based on your listening activity',
        autoProgressSection: 'Status Automation',
        autoProgressMarked: 'Mark on Visit',
        autoProgressMarkedDesc: 'Set status to Marked when you visit a work page',
        autoProgressListening: 'Mark Listening',
        autoProgressListeningDesc: 'Set status to Listening after 5 seconds of playback',
        autoProgressListened: 'Mark Listened',
        autoProgressListenedDesc: 'Set status to Listened when the last track reaches 85%',
        autoProgressReplay: 'Track Replays',
        autoProgressReplayDesc: 'Set status to Replay after multiple complete listens',
        autoProgressPostponed: 'Mark Postponed',
        autoProgressPostponedDesc: 'Set status to Postponed when less than 30% of tracks are played',
        autoProgressReplayThreshold: 'Replay Count',
        autoProgressReplayThresholdDesc: 'Number of complete listens before marking as Replay',
        autoProgressRadioSkipThreshold: 'Postpone Visit Limit',
        autoProgressRadioSkipThresholdDesc: 'Visits without listening before marking as Postponed',

        // Settings - Whisper
        embeddingModelReady: 'Embedding model ready.',
        embeddingLoading: 'Loading embedding model...',
        embeddingLoadingFile: 'Loading embedding model: {file}',
        clearTranslationCache: 'Clear Translation Cache',
        clearTranslationCacheSub: 'Remove all cached translations to force re-translation',
        clearTranslationCacheConfirm: 'Clear all cached translations?',
        clearTranslationCacheSuccess: 'Cleared {count} cached translations.',
        downloadWhisperModel: 'Download Whisper Model',
        downloadWhisperModelSub: 'Pre-load the Whisper model to avoid delay on first use',
        downloadWhisperModelReady: 'Whisper model ready.',
        downloadWhisperModelFailed: 'Whisper model download failed: {message}',
        downloadWhisperModelLoading: 'Downloading Whisper model',
        whisperSettings: 'Whisper Settings',
        translationSettings: 'Translation Settings',

        // Settings - Storage
        storageData: 'Storage & Data',
        factoryReset: 'Factory Reset',
        factoryResetSub: 'Delete all cached data, settings, and databases',
        factoryResetConfirm: 'This will erase ALL plugin data (audio cache, vector index, tag translations, and settings). Continue?',
        factoryResetConfirm2: 'Are you absolutely sure? This cannot be undone.',
        factoryResetting: 'Resetting...',
        backupSettings: 'Backup Settings',
        backupSettingsSub: 'Download current settings as JSON before resetting',
        restoreSettings: 'Restore Settings',
        restoreSettingsSub: 'Upload a previously saved JSON backup',
        restoreSuccess: 'Restored {count} settings. Reloading...',
        restoreFailed: 'Failed to restore settings. Is the file valid JSON?',
        generalSettings: 'General Settings',
        enableLogging: 'Enable Console Logging',
        enableLoggingSub: 'Log technical info to console (recommended for debugging)',

        // DLsite Proxy
        dlsiteProxy: 'DLsite Proxy',
        dlsiteProxySub: 'URL of your Cloudflare Worker proxy to bypass region blocks',
        dlsiteProxySetup: 'Setup Guide',

        // API Server
        apiServer: 'API Server',
        apiServerSub: 'Select the ASMR.one API server (mirror)',
        dlsiteProxyUrl: 'Proxy URL',
        dlsiteProxyUrlSub: 'Unlocks DLsite comments and metadata restricted to Japan. Setup is free and easy.',
        dlsiteProxyUrlSetup: 'View Full Setup Guide',
        dlsiteProxyFullGuide: '<h4>Cloudflare Proxy Setup Guide</h4>' +
            '<p>1. Go to <a href="https://dash.cloudflare.com/" target="_blank" class="text-primary asmr-settings-link">Cloudflare Dashboard</a> and login.</p>' +
            '<p>2. Navigate to <b>Compute & AI</b> > <b>Workers & Pages</b> and click <b>Create</b>.</p>' +
            '<p>3. Name it <code>dlsite-proxy</code> and click <b>Deploy</b>.</p>' +
            '<p>4. Click <b>Edit Code</b>, delete the default "Hello World" code, and paste the block below.</p>' +
            '<p>5. Click <b>Deploy</b> (top-right).</p>' +
            '<p>6. Go to <b>Settings</b> > <b>General</b> > <b>Placement</b>. Select <b>Region</b>, set provider to <b>Microsoft Azure</b>, and region to <b>japaneast</b>.</p>' +
            '<p>7. Copy the worker URL and paste it into the Proxy URL field.</p>',
        dlsiteProxyWorkerCode: 'Worker Proxy Code',
        copyCode: 'Copy Code',
        copied: 'Copied!',

        // Semantic Search (VectorSearch)
        magicSearch: 'Semantic Search',
        magicSearchBtn: 'Semantic Search',
        magicSearchPlaceholder: "Describe functionality (e.g. 'relaxing')...",
        magicSearchGo: 'Search',
        magicSearchPrev: 'Prev',
        magicSearchNext: 'Next',
        magicSearchReady: 'Ready.',
        magicSearchSearching: 'Searching...',
        magicSearchSearchingJP: 'Searching (JP translation applied)...',
        magicSearchPreparing: 'Preparing search...',
        magicSearchNoMatches: 'No matches found.',
        magicSearchNoRelevantMatches: 'No relevant matches found. Try different search terms.',
        magicSearchWorksIndexed: '{count} works indexed',
        magicSearchMatch: '% Match',
        magicSearchPage: 'Page {current} / {total}',
        magicSearchShowing: 'Showing {start}-{end} of {total}',
        magicSearchEmbedFail: 'Failed to generate embedding. Check console for errors.',
        magicSearchIndexEmpty: 'Index is empty. Auto-indexing recent works...',
        magicSearchIndexEmptyCheck: 'Index is still empty. Check Console for errors.',
        magicSearchCooldown: 'System cooling down (+{wait}s). Please wait...',
        magicSearchFetchingLatest: 'Fetching latest works...',
        magicSearchFetchingPage: 'Fetching page {page}/{end}...',
        magicSearchWorksRateLimited: 'Works API rate limited. Retrying later...',
        magicSearchIndexingPage: 'Indexing page {page} ({count} works)...',
        magicSearchIndexingContinue: 'Indexed {indexed} works (page {cursor} next). Total: {total}. Next batch in ~{delay}s...',
        magicSearchIndexingPaused: 'Indexing complete ({total} works). Watching for new works...',
        magicSearchBulkIndexFailed: 'Bulk index failed.',
        magicSearchRateLimitedRetry: 'Rate limited. Retry in {wait}s...',
        magicSearchTimeout: 'Search timed out. Try a simpler query.',
        magicSearchCancelled: 'Search cancelled.',
        magicSearchCancel: 'Cancel',

        // Advanced Search
        advSearch: 'Advanced Search',
        advSearchBtn: 'Advanced Search / Playlist Maker',
        advIncludeTags: 'Include Tags',
        advExcludeTags: 'Exclude Tags',
        advFilterTags: 'Type to filter tags...',
        advVoiceActor: 'Voice Actor (CV)',
        advSearchVA: 'Search voice actors...',
        advCircle: 'Circle',
        advSearchCircle: 'Search circles...',
        advDuration: 'Duration (Minutes)',
        advSortBy: 'Sort By',
        advMinRating: 'Min Rating',
        advMinPrice: 'Min Price (¥)',
        advMinSales: 'Min Sales',
        advAgeRating: 'Age Rating',
        advLanguage: 'Language',
        advMinPlaceholder: 'Min',
        advMaxPlaceholder: 'Max',
        advMinDurationAria: 'Minimum duration (minutes)',
        advMaxDurationAria: 'Maximum duration (minutes)',
        advPresetShortTitle: '0-30 min',
        advPresetShortAria: '0 to 30 minutes',
        advPresetMediumTitle: '30-120 min',
        advPresetMediumAria: '30 to 120 minutes',
        advPresetLongTitle: '120+ min',
        advPresetLongAria: '120 minutes or more',
        advSortDescAria: 'Descending order',
        advSortAscAria: 'Ascending order',
        advMinRatingPlaceholder: 'e.g. 4.0',
        advMinPricePlaceholder: 'e.g. 500',
        advMinSalesPlaceholder: 'e.g. 1000',
        advLangJa: 'Japanese (日本語)',
        advLangEn: 'English',
        advLangKo: 'Korean (한국어)',
        advLangZhCn: 'Chinese Simplified (简体中文)',
        advLangZhTw: 'Chinese Traditional (繁體中文)',
        advRemoveTag: 'Remove {tag}',
        advRemoveVA: 'Remove VA {name}',
        advRemoveCircle: 'Remove Circle {name}',
        advSearchAction: 'Search',
        advCreatePlaylist: 'Create Playlist',
        advWorks: 'Works:',
        advDesc: 'Desc',
        advAsc: 'Asc',
        advShort: 'Short',
        advMedium: 'Medium',
        advLong: 'Long',
        advAny: 'Any',
        advAllAges: 'All Ages (全年齢)',
        advAdult: 'Adult (18+)',
        advNoResults: 'No results found',
        advLoadingTags: 'Loading tags...',
        advLoadingVA: 'Loading voice actors...',
        advLoadingCircles: 'Loading circles...',
        advSearching: 'Searching...',
        advFetching: 'Fetching page {page}/{max}...',
        advNoWorks: 'No works found.',
        advFound: 'Found {count} works.',
        advCancelled: 'Cancelled.',
        advCreatingPlaylist: 'Creating playlist...',
        advPlaylistCreated: 'Playlist created! Redirecting...',
        advPlaylistFailed: 'Failed to create playlist. See console.',
        advSearchFailed: 'Search failed. See console.',
        advCancelling: 'Cancelling...',
        advFindingWorks: 'Finding works...',
        advNoWorksPlaylist: 'No works found for playlist.',
        advGoToWork: 'Go to work',
        advPlaylistDesc: 'Smart selection of {count} works from a pool of {pool} candidates.',
        advPlaylistParams: 'Filters',

        // Sort options
        sortNewest: 'Newest',
        sortRelease: 'Release Date',
        sortRating: 'User Rating',
        sortDownloads: 'Downloads',
        sortReviews: 'Reviews',
        sortPrice: 'Price',
        sortDlsiteRating: 'DLsite Rating',
        sortNSFW: 'NSFW',
        sortRandom: 'Random',
        sortRJCode: 'RJ Code',

        // About & Links
        aboutHeader: 'About',
        readmeDocs: 'Documentation & Source',
        readmeDocsSub: 'Full feature guide, architecture docs, and source code on GitHub',
        reportIssue: 'Report an Issue',
        reportIssueSub: 'Found a bug or have a feature request? Open an issue on GitHub',
        discordLabel: 'Discord',
        discordSub: 'Questions, suggestions, or just want to chat? Add me on Discord: henry281199',
        discordCopy: 'Copy username',
        donateLabel: 'Support Development',
        donateSub: 'This project is built and maintained by a single developer in their spare time — over £300 has gone into AI subscriptions alone to make features like live transcription and translation possible. It will always be free. If it has made your experience better, a small donation helps cover these costs and motivates continued development.',

        // Credits
        creditsHeader: 'Credits & Acknowledgements',
        creditsSub: 'Building on the shoulders of giants. Special thanks to these projects and creators:',
        creditsAsmrOnline: 'Host platform',
        creditsKikoeru: 'Core media server and player',
        creditsCollections: 'Semantic search inspiration',
        creditsSubtitleTranslator: 'Original subtitle translator script',
        creditsDLsite: 'Content and metadata provider',
        creditsYuro: 'Community mobile client',
        creditsTampermonkey: 'Userscript runtime providing GM_* APIs',
        creditsWhisper: 'Speech recognition model',
        creditsXenova: 'ONNX model conversions for browser inference',
        creditsGoogleTranslate: 'Fallback translation service',
        creditsTransformers: 'Browser-based ML inference engine',
        creditsONNXRuntime: 'Cross-platform ML inference runtime',
        creditsHuggingFace: 'ML model hosting and distribution',
        creditsVue: 'Progressive JavaScript UI framework',
        creditsQuasar: 'Vue UI component framework (host app)',
        creditsPdfJs: 'PDF rendering and text extraction',
        creditsIdb: 'IndexedDB wrapper for local storage',
        creditsFuseJs: 'Fuzzy search library',
        creditsVitePluginMonkey: 'Vite-based userscript build tool',
        creditsMaterialIcons: 'Icon font used throughout the UI',
        creditsHVDB: 'Voice work metadata cross-reference database',
        creditsChobit: 'Alternative voice work search engine',
        creditsH2k: 'Japanese frequency data for translation glossary',

        // Metadata Panel
        metaShowDetails: 'Show DLsite Details',
        metaHideDetails: 'Hide DLsite Details',
        metaRefresh: 'Refresh metadata',
        metaFileContents: 'File Contents ({count})',

        // Playlist Controls
        playlistPrevWork: 'Previous Work',
        playlistNextWork: 'Next Work',
        playlistPublicTitle: 'Public Playlists',
        playlistFindMore: 'Find More',
        playlistRandomize: 'Randomize',
        playlistRandomizing: 'Shuffling...',
        playlistFilterPlaceholder: 'Filter playlists...',
        playlistOnlineOnly: 'Online only',
        playlistLoadMore: 'Load More',
        playlistLoadingMore: 'Loading more...',
        playlistLoadingDone: 'All playlists loaded.',
        playlistLoadingUser: 'Fetching your playlists...',
        playlistLoadStatus: 'Loaded {loaded}/{total}',
        playlistLoadStatusDone: 'Loaded {loaded}/{total} (done)',
        playlistSearching: 'Searching Google for public playlists...',
        playlistSearchingPage: 'Searching page {page}... Found {found} playlists',
        playlistSearchingButton: 'Searching...',
        playlistSearchFailed: 'Search failed. Please try again.',
        playlistDiscoverTitle: 'Discover Public Playlists',
        playlistDiscoverHint: 'No public playlists discovered yet. Click "{action}" to find indexed playlists, or add a playlist URL manually.',
        playlistLoadFailed: 'Failed to load public playlists. Please try again later.',
        playlistAddPlaceholder: 'Paste playlist URL or ID...',
        playlistAddButton: 'Add',
        playlistAddedBadge: 'Added',
        playlistFilterAll: 'All',
        playlistFilterMine: 'Mine',
        playlistFilterPublic: 'Public Only',
        playlistsTitle: 'Playlists',

        // Work Tree
        flatView: 'Flat View',
        fileListHeader: 'All Files',
        fileListCount: '{count} files',
        fileListClose: 'Close file list',
        autoFilterFolders: 'Auto-Navigate Folders',
        autoFilterFoldersSub: 'Skip to the best content folder automatically',

        // Playback Speed
        speedTitle: 'Speed: {rate}x',

        // Learner Mode Overflow
        more: 'More',
        aiTranscribe: 'AI Auto-Transcribe',
        openWorkDetail: 'Open work detail',
        loadSubtitle: 'Load local subtitle',
        downloadTrack: 'Download Track',

        // Whisper Status
        whisperLoading: 'Loading model...',
        whisperTranscribing: 'Transcribing...',
        whisperTranslating: 'Translating {count} segments...',
        whisperError: 'AI Error: {message}',
        whisperBtnLabel: 'AI Transcribe',
        whisperBtnTitle: 'Transcribe audio with Whisper AI',
        whisperTranscriptDownload: 'LRC',
        whisperTranscriptDownloadLang: 'LRC ({lang})',
        vttDownload: 'VTT',
        vttDownloadTranslated: 'VTT (translated)',
        whisperHlsWarning: 'HLS streaming detected — transcription requires a downloadable audio file.',
        whisperStatus: 'Transcription status',
        whisperComplete: 'Transcription complete',
        whisperReady: 'Whisper is ready',
        whisperChunkProgress: 'Transcribing… {current}s / {total}s',
        whisperExistingSubs: 'Subtitles already available. Transcribe anyway?',
        whisperInit: 'Initializing...',
        whisperLoadingModelAudio: 'Loading model + fetching audio...',
        whisperFetchingAudio: 'Fetching audio...',
        whisperDecodingAudio: 'Decoding audio...',
        whisperWaitingForModel: 'Waiting for model...',
        whisperPreparingFirstChunk: 'Preparing first chunk...',
        whisperStreamingAudio: 'Streaming audio... {loaded}/{total} MB',
        whisperDownloadingAudio: 'Downloading audio... {loaded}/{total} MB',
        whisperInitializingModel: 'Initializing model (this may take a moment)...',
        whisperLoadingModelFile: 'Loading model: {file} ({progress}%)',
        whisperLoadingFile: 'Loading: {file}',
        whisperTranscribingElapsed: 'Transcribing... {elapsed}s{segments}',
        whisperSegmentCount: ' · {count} segments',
        whisperFallbackModel: 'Model load failed. Falling back to {model}...',
        whisperFallbackApplied: 'Switched to {model} ({reason})',
        whisperForceWasm: 'WebGPU failed. Switching to WASM...',
        whisperWarmupTimeout: 'Model warmup timed out',
        whisperWarmupFailed: 'Model warmup failed',
        whisperWarmupFailedDetail: 'Model warmup failed: {message}',
        whisperWebGpuFallback: 'WebGPU produced empty result. Retrying with WASM...',
        whisperWebGpuRequired: 'WebGPU is required for live transcription.',
        whisperNoAudioSource: 'No audio source found. Please play a track first.',
        whisperFetchAudioFailed: 'Failed to fetch audio. Check network or CORS.',
        whisperAudioCorrupted: 'Audio data is corrupted. Try a different file.',
        whisperAudioProcessingFailed: 'Audio processing failed: {message}',
        whisperWorkerError: 'Worker error: {message}',
        whisperTranscriptionError: 'Transcription error: {message}',
        whisperRecovering: 'GPU error — restarting on CPU...',
        whisperGpuCrashed: 'GPU crashed — please refresh the page. If the problem persists, restart your browser.',
        whisperUnknownError: 'Unknown error',

        // WorkTreeCopy
        copyBtn: 'Copy',
        copiedNotify: 'Copied: {text}',

        // Comment Section
        commentsHeader: 'Listener Community',
        commentsMyReview: 'Share Your Experience',
        commentsDLsite: 'From DLsite Listeners',
        commentsPlaceholder: 'How was the performance? Share your thoughts with the community...',
        commentsSaving: 'Saving...',
        commentsSaved: 'Saved',
        commentsSaveFailed: 'Save failed',
        commentsTranslate: 'Translate',
        commentsShowOriginal: 'Show Original',
        commentsLoading: 'Loading reviews...',
        commentsNoReviews: 'No reviews found',
        commentsDelete: 'Remove My Thoughts',
        commentsDeleteConfirm: 'Delete your review for this work?',
        commentsCount: '{count} reviews',
        commentsExpand: 'Show Reviews',
        commentsCollapse: 'Hide Reviews',
        commentsFetchFailed: 'Failed to fetch DLsite reviews. Check your Proxy URL in Settings.',

        // Media Viewer
        mediaViewerPdfLoadFailed: 'Failed to load PDF',
        mediaViewerTextLoadFailed: 'Failed to load text file',
        mediaViewerTextTruncated: 'Preview limited to {count} KB',

        // SFW Mode
        sfwMode: 'SFW Mode',
        sfwModeSub: 'Hide all images and thumbnails for public viewing',

        // Translation Toggle
        translateMode: 'Translations',
        translateModeSub: 'Translate tags, titles, and UI elements (reload required)',
        translateCnToJp: 'Chinese → Japanese',
        translateCnToJpSub: 'Silently replace Chinese text with Japanese, with or without translations',

        // Feature Toggles (Global)
        featureToggles: 'Feature Toggles',
        enablePlaylistDiscovery: 'Playlist Discovery',
        enablePlaylistDiscoverySub: 'Find shared playlists via Google Search',
        enableLearnerMode: 'Learner Mode',
        enableLearnerModeSub: 'Bilingual subtitles and controls',
        learnerBlurLabel: 'Blur Translations',
        learnerBlurSub: 'Start with translations blurred (reveal on hover or click)',
        karaokeMode: 'Karaoke Mode',
        karaokeModeSub: 'Highlight the current word with accent color as it is spoken',
        segmentMode: 'Segment Mode',
        segmentModeSub: 'Show upcoming words (dimmed) instead of hiding them',
        enableAdvancedSearch: 'Advanced Search',
        enableAdvancedSearchSub: 'Filter by tags, CV, circle, duration',
        enableWorkMetadata: 'Enhanced Metadata',
        enableWorkMetadataSub: 'Show expanded metadata and DLsite info',
        enablePlayerTranslator: 'Player Translator',
        enablePlayerTranslatorSub: 'Translate player interface',
        enableSupportButton: 'Support Button',
        enableSupportButtonSub: 'Show support/feedback link',
        enableWorkTreeManager: 'Folder Diver & Flat View',
        enableWorkTreeManagerSub: 'Automatic folder navigation and flattened view',
        enableTagFilters: 'Tag Filters',
        enableTagFiltersSub: 'Hide works with specific tags',
        enableVectorSearch: 'Semantic Search',
        enableVectorSearchSub: 'AI-powered search — initial indexing may take about a day',
        enableWhisper: 'Whisper',
        enableWhisperSub: 'Local AI transcription',
        alwaysTranscribe: 'Auto-Transcribe',
        alwaysTranscribeSub: 'Automatically transcribe when a new track starts playing',
        forceWhisperWasm: 'Force CPU Mode (WASM)',
        forceWhisperWasmSub: 'Disable WebGPU for Whisper and run on CPU for better compatibility on weak GPUs',
        enableFavicon: 'Dynamic Favicon',
        enableFaviconSub: 'Update tab icon with cover art',
        enableMediaSession: 'Media Session',
        enableMediaSessionSub: 'System media controls support',
        enableMenuIconFixer: 'Menu Icon Fixer',
        enableMenuIconFixerSub: 'Fix missing icons in sidebar',
        enableStoreBackup: 'Store Backup',
        enableStoreBackupSub: 'Backup/Restore plugin data',
        enableHVDBLink: 'HVDB Link',
        enableHVDBLinkSub: 'Link to HVDB metadata',
        enableInterfaceTranslator: 'Interface Translator',
        enableInterfaceTranslatorSub: 'Translate UI elements',
        enablePageTitleManager: 'Page Title Manager',
        enablePageTitleManagerSub: 'Fix tab title display',
        enableKeyboardManager: 'Keyboard Shortcuts',
        enableKeyboardManagerSub: 'Custom hotkeys',
        enableRouteStateSync: 'Route State Sync',
        enableRouteStateSyncSub: 'Sync app state with URL',
        enableMediaViewer: 'Media Viewer',
        enableMediaViewerSub: 'Preview images/videos in lightbox',
        enablePlayerFullscreen: 'Fullscreen Player',
        enablePlayerFullscreenSub: 'Toggle fullscreen mode for the expanded player',
        enablePlayerGallery: 'Player Gallery',
        enablePlayerGallerySub: 'Browse work images in the player cover art area',
        fullscreenToggle: 'Fullscreen',
        fullscreenExit: 'Exit Fullscreen',
        galleryPrev: 'Previous image',
        galleryNext: 'Next image',
        galleryExclude: 'Hide this image',
        gallerySlideshowPause: 'Pause slideshow',
        gallerySlideshowResume: 'Resume slideshow',
        galleryAutoSlideshow: 'Auto Slideshow',
        galleryAutoSlideshowSub: 'Automatically cycle through images in fullscreen and lightbox',
        galleryAutoSlideshowInterval: 'Slideshow Interval',
        galleryAutoSlideshowIntervalSub: 'Seconds between image transitions',
        keyboardShortcuts: 'Keyboard Shortcuts',
        hotkeyPlayPause: 'Play / Pause',
        hotkeyMute: 'Mute',
        hotkeyFullscreen: 'Fullscreen',
        hotkeySeekBack: 'Seek Back (5s)',
        hotkeySeekForward: 'Seek Forward (5s)',
        hotkeySeekBackLong: 'Seek Back (10s)',
        hotkeySeekForwardLong: 'Seek Forward (10s)',
        hotkeyVolumeUp: 'Volume Up',
        hotkeyVolumeDown: 'Volume Down',
        hotkeyPrevLine: 'Previous Line / Track',
        hotkeyNextLine: 'Next Line / Track',
        hotkeyPrevTrack: 'Previous Track',
        hotkeyNextTrack: 'Next Track',
        hotkeySpeedUp: 'Speed Up',
        hotkeySpeedDown: 'Speed Down',
        hotkeyToggleBlur: 'Toggle Blur',
        revealTranslation: 'Reveal translation',
        hideTranslation: 'Hide translation',
        hotkeyToggleJP: 'Toggle Japanese',
        hotkeySpeedReset: 'Reset Speed',
        hotkeyGalleryExclude: 'Hide Image (Gallery)',
        hotkeyGalleryPrev: 'Gallery Previous',
        hotkeyGalleryNext: 'Gallery Next',
        hotkeyPressKey: 'Press a key…',
        hotkeyReset: 'Reset to default',
        enableWorkTreeCopy: 'Copy Button',
        enableWorkTreeCopySub: 'Copy file names in file explorer',
        enableCommentSection: 'Comments',
        enableCommentSectionSub: 'Show DLsite reviews/comments',
        enableInfiniteScroll: 'Infinite Scroll',
        enableInfiniteScrollSub: 'Auto-load more content when scrolling',
        infScrollEndOfResults: 'End of results',
        infScrollRateLimitRetry: 'Rate limited. Retrying in {seconds}s...',
        infScrollRateLimitError: 'Rate limited. Please wait a moment before scrolling.',
        infScrollLoadingImages: 'Loading {count} images...',
        infScrollSales: 'Sales: {count}',
        infScrollAllAges: 'All-ages',

        // JOI Tool
        enableJoiTool: 'JOI Tool',
        enableJoiToolSub: 'Interactive edge game synced with live transcription',
        alwaysShowJoi: 'Always Show JOI',
        alwaysShowJoiSub: 'Automatically activate JOI tool when audio plays',
        joiTool: 'JOI Tool',
        joiToggle: 'Toggle JOI',
        joiGo: 'GO',
        joiStop: 'STOP',
        joiEdge: 'EDGE',
        joiCum: 'CUM',
        joiDenied: 'DENIED',
        joiRuined: 'RUINED',
        joiIdle: 'READY',
        joiGoSlow: 'Slow and steady...',
        joiGoFast: 'Pick up the pace...',
        joiGoGentle: 'Gentle strokes...',
        joiStopHands: 'Hands off!',
        joiStopWait: 'Hold it...',
        joiStopBreathe: 'Breathe...',
        joiEdgeClose: 'Right on the edge...',
        joiEdgeHold: 'Hold it there...',
        joiEdgeDanger: 'Careful now...',
        joiCumNow: 'NOW!',
        joiDeniedMsg: 'Not this time.',
        joiRuinedMsg: 'Too late...',
        joiResuming: 'Resuming in {sec}s...',
        joiNoWhisper: 'Enable Whisper first',
        joiActivated: 'JOI activated',
        joiDeactivated: 'JOI deactivated',

        // Visualizer
        enableVisualizer: 'Sound Visualizer',
        enableVisualizerSub: 'Real-time audio frequency visualization bar',
        alwaysShowVisualizer: 'Always Show Visualizer',
        alwaysShowVisualizerSub: 'Automatically activate visualizer when audio plays',
        vizToggle: 'Toggle Visualizer',

        // Visit Counter
        enableVisitCounter: 'Visit Counter',
        enableVisitCounterSub: 'Show how many times you have opened each work',

        // Continue Listening
        enableContinueListening: 'Continue Listening',
        enableContinueListeningSub: 'Show works with "listening" status on the homepage',
        continueListeningTitle: 'Continue Listening',

        // JPDB Integration
        jpdbSection: 'JPDB Integration',
        enableJpdb: 'Enable JPDB',
        enableJpdbSub: 'Furigana, pitch accent, and vocabulary tracking via jpdb.io',
        jpdbApiToken: 'API Token',
        jpdbApiTokenSub: 'Free account required — copy from your jpdb.io settings page',
        jpdbApiTokenPlaceholder: 'Paste your jpdb.io API key',
        jpdbGetApiKey: 'Get API Key from jpdb.io',
        jpdbShowFurigana: 'Show Furigana',
        jpdbShowFuriganaSub: 'Display reading annotations above kanji',
        jpdbShowPitchAccent: 'Pitch Accent',
        jpdbShowPitchAccentSub: 'Show pitch accent patterns on words (overrides word status underlines)',
        jpdbSiteFurigana: 'Sitewide Furigana',
        jpdbSiteFuriganaSub: 'Add furigana to titles, tags, and page content',
        jpdbSubtitleFurigana: 'Subtitle Furigana',
        jpdbSubtitleFuriganaSub: 'Add furigana to subtitles in Learner Mode',
        jpdbPitchStyle: 'Pitch Style',
        jpdbPitchStyleSub: 'How pitch accent is displayed',
        jpdbPitchUnderline: 'Underline',
        jpdbPitchColor: 'Color',
        jpdbPitchBoth: 'Both',
        jpdbPitchOff: 'Off',
        hotkeyJpdbPopover: 'Word Popover',
        jpdbMiningDeck: 'Mining Deck',
        jpdbMiningDeckSub: 'Deck to add mined words to (leave empty for FORQ)',
        jpdbMiningDeckPlaceholder: 'forq',
        jpdbAddToForq: 'Add to FORQ',
        jpdbAddToForqSub: 'Also add mined words to the FORQ deck',
        jpdbDisableReviews: 'Disable Reviews',
        jpdbDisableReviewsSub: 'Hide review grading buttons in the popover',
        jpdbUseTwoGrades: '2-Point Grading',
        jpdbUseTwoGradesSub: 'Use Fail/Pass instead of 5-point scale',
        jpdbNeverForgetDeck: 'Never Forget Deck',
        jpdbNeverForgetDeckSub: 'Deck ID for never-forget words',
        jpdbBlacklistDeck: 'Blacklist Deck',
        jpdbBlacklistDeckSub: 'Deck ID for blacklisted words',
        jpdbPopoverNoKey: 'Set up a jpdb.io API key to track vocabulary',
        jpdbPopoverGetKey: 'Get API Key',
        jpdbPopoverRank: 'Rank',
        jpdbPopoverState: 'State',
        jpdbBtnAdd: 'Add',
        jpdbBtnNeverForget: 'Never forget',
        jpdbBtnForget: 'Forget',
        jpdbBtnBlacklist: 'Blacklist',
        jpdbBtnUnlist: 'Unlist',
        jpdbGradeNothing: 'NOTHING',
        jpdbGradeSomething: 'SOMETHING',
        jpdbGradeHard: 'HARD',
        jpdbGradeOkay: 'OKAY',
        jpdbGradeEasy: 'EASY',
        jpdbGradeFail: 'FAIL',
        jpdbGradePass: 'PASS',
        jpdbStateNew: 'New',
        jpdbStateLearning: 'Learning',
        jpdbStateKnown: 'Known',
        jpdbStateDue: 'Due',
        jpdbStateFailed: 'Failed',
        jpdbStateLocked: 'Locked',
        jpdbStateNotInDeck: 'Not in deck',
        jpdbStateSuspended: 'Suspended',
        jpdbStateBlacklisted: 'Blacklisted',
        jpdbStateNeverForget: 'Never forget',
        jpdbStateRedundant: 'Redundant',
        jpdbCredits: 'Furigana & vocabulary powered by jpdb.io',
        jpdbCreditsReader: 'Reading parser based on anki-jpdb.reader by chinokusari',
    },
    zh: {
        // Settings - Radio
        radioMode: '电台模式',
        off: '关闭',
        on: '开启',
        radioStatusIdle: '待机',
        radioStatusStarting: '准备播放...',
        radioStatusLoading: '正在加载作品...',
        radioStatusSkipping: '正在跳转到下一部作品...',
        radioStatusPlaying: '播放中',
        radioSettings: '电台设置',
        playlistSettings: '播放列表设置',
        playAll: '播放整个作品',
        playAllSub: '播放完队列中所有曲目后再跳转到下一个作品',
        radioFlatTracks: '音轨池：全部文件夹',
        radioFlatTracksSub: '从整个目录树收集音轨，而不是只用单个已选文件夹',
        trackPoolAllFolders: '音轨池：全部文件夹',
        trackPoolAllFoldersSub: '从整个作品目录树构建播放队列。关闭“播放整个作品”时，将从该池中只选一首播放。',
        folderPoolSettings: '文件夹与音轨池设置',
        shuffle: '随机播放',
        shuffleSub: '打乱播放顺序',
        loopPlaylist: '循环',
        loopPlaylistSub: '播放列表结束后从头开始',
        prefFormat: '偏好格式',
        prefFormatSub: '例如 wav, mp3',
        sePref: 'SE 偏好',
        sePrefSub: '优先进入包含音效 (SE) 的目录',
        bgmPref: 'BGM 偏好',
        bgmPrefSub: '优先进入包含背景音乐 (BGM) 的目录',
        primaryLang: '主字幕语言',
        primaryLangSub: '主字幕的语言代码 (如 ja, en)',
        targetLang: '副字幕语言',
        targetLangSub: '副字幕的语言代码 (如 en, es)',
        liveCaptionTitle: '小贴士: 实时字幕',
        liveCaptionMsg: '建议配合系统实时字幕功能使用！',
        prevLine: '上一句',
        nextLine: '下一句',
        toggleJP: '切换日语显示',
        autoProgress: '状态追踪',
        autoProgressSub: '根据收听行为自动更新作品状态',
        autoProgressSection: '状态自动化',
        autoProgressMarked: '访问即标记',
        autoProgressMarkedDesc: '访问作品页面时标记为想听',
        autoProgressListening: '播放即标记',
        autoProgressListeningDesc: '播放超过5秒后标记为在听',
        autoProgressListened: '听完即标记',
        autoProgressListenedDesc: '最后一个音轨播放到85%时标记为听过',
        autoProgressReplay: '重听追踪',
        autoProgressReplayDesc: '完整收听多次后标记为重听',
        autoProgressPostponed: '搁置标记',
        autoProgressPostponedDesc: '播放不到30%的音轨就离开时标记为搁置',
        autoProgressReplayThreshold: '重听次数',
        autoProgressReplayThresholdDesc: '完整收听几次后标记为重听',
        autoProgressRadioSkipThreshold: '搁置访问上限',
        autoProgressRadioSkipThresholdDesc: '未收听的访问次数达到此值后标记为搁置',

        // Settings - Whisper
        embeddingModelReady: '嵌入模型已就绪。',
        embeddingLoading: '正在加载嵌入模型...',
        embeddingLoadingFile: '正在加载嵌入模型：{file}',
        clearTranslationCache: '清除翻译缓存',
        clearTranslationCacheSub: '删除所有缓存的翻译以强制重新翻译',
        clearTranslationCacheConfirm: '清除所有缓存的翻译？',
        clearTranslationCacheSuccess: '已清除 {count} 条缓存翻译。',
        downloadWhisperModel: '下载 Whisper 模型',
        downloadWhisperModelSub: '预加载 Whisper 模型，避免首次使用时的延迟',
        downloadWhisperModelReady: 'Whisper 模型已就绪。',
        downloadWhisperModelFailed: 'Whisper 模型下载失败：{message}',
        downloadWhisperModelLoading: '正在下载 Whisper 模型',
        whisperSettings: 'Whisper 设置',
        translationSettings: '翻译设置',

        // Settings - Storage
        storageData: '存储与数据',
        factoryReset: '恢复出厂设置',
        factoryResetSub: '删除所有缓存数据、设置和数据库',
        factoryResetConfirm: '这将清除所有插件数据（音频缓存、向量索引、标签翻译和设置）。继续？',
        factoryResetConfirm2: '你确定吗？此操作无法撤销。',
        factoryResetting: '正在重置...',
        backupSettings: '备份设置',
        backupSettingsSub: '重置前将当前设置下载为 JSON',
        restoreSettings: '恢复设置',
        restoreSettingsSub: '上传之前保存的 JSON 备份',
        restoreSuccess: '已恢复 {count} 项设置。正在重新加载...',
        restoreFailed: '恢复设置失败。文件是有效的 JSON 吗？',
        generalSettings: '常规设置',
        enableLogging: '启用控制台日志',
        enableLoggingSub: '在控制台输出技术信息（建议在调试时开启）',

        // DLsite Proxy
        dlsiteProxy: 'DLsite 代理',
        dlsiteProxySub: 'Cloudflare Worker 代理 URL，用于绕过地区限制',
        dlsiteProxySetup: '如何搭建',

        // API Server
        apiServer: 'API 服务器',
        apiServerSub: '选择 ASMR.one API 服务器 (镜像站)',
        dlsiteProxyUrl: '代理 URL',
        dlsiteProxyUrlSub: '解锁受日本地区限制的 DLsite 评论和元数据。设置简单且免费。',
        dlsiteProxyUrlSetup: '查看完整设置指南',
        dlsiteProxyFullGuide: '<h4>Cloudflare 代理设置指南</h4>' +
            '<p>1. 登录 <a href="https://dash.cloudflare.com/" target="_blank" class="text-primary asmr-settings-link">Cloudflare 控制台</a>。</p>' +
            '<p>2. 进入 <b>Compute & AI</b> > <b>Workers & Pages</b>，点击 <b>Create</b>。</p>' +
            '<p>3. 命名为 <code>dlsite-proxy</code> 并点击 <b>Deploy</b>。</p>' +
            '<p>4. 点击 <b>Edit Code</b>，删除默认代码，粘贴下方的代码块。</p>' +
            '<p>5. 点击右上角的 <b>Deploy</b>。</p>' +
            '<p>6. 进入 <b>Settings</b> > <b>General</b> > <b>Placement</b>。选择 <b>Region</b>，将提供商设为 <b>Microsoft Azure</b>，并将区域设置为 <b>japaneast</b>。</p>' +
            '<p>7. 复制生成的 URL 并粘贴到插件设置的“代理 URL”中。</p>',
        dlsiteProxyWorkerCode: 'Worker 代理代码',
        copyCode: '复制代码',
        copied: '已复制！',

        // Semantic Search (VectorSearch)
        magicSearch: '语义搜索',
        magicSearchBtn: '语义搜索',
        magicSearchPlaceholder: "描述功能（例如 '纯粹的耳朵清洁'）...",
        magicSearchGo: '搜索',
        magicSearchPrev: '上一页',
        magicSearchNext: '下一页',
        magicSearchReady: '就绪。',
        magicSearchSearching: '搜索中...',
        magicSearchSearchingJP: '搜索中（已应用日语翻译）...',
        magicSearchPreparing: '准备搜索...',
        magicSearchNoMatches: '未找到匹配。',
        magicSearchNoRelevantMatches: '未找到相关匹配。请尝试不同的搜索词。',
        magicSearchWorksIndexed: '{count} 个作品已索引',
        magicSearchMatch: '% 匹配',
        magicSearchPage: '第 {current} / {total} 页',
        magicSearchShowing: '显示 {start}-{end}，共 {total}',
        magicSearchEmbedFail: '生成嵌入失败。请检查控制台错误。',
        magicSearchIndexEmpty: '索引为空。正在自动索引最近的作品...',
        magicSearchIndexEmptyCheck: '索引仍然为空。请检查控制台错误。',
        magicSearchCooldown: '系统冷却中（+{wait}秒）。请稍候...',
        magicSearchFetchingLatest: '正在获取最新作品...',
        magicSearchFetchingPage: '正在获取第 {page}/{end} 页...',
        magicSearchWorksRateLimited: '作品 API 触发限流。稍后重试...',
        magicSearchIndexingPage: '正在索引第 {page} 页（{count} 部作品）...',
        magicSearchIndexingContinue: '已索引 {indexed} 部作品（下一页 {cursor}）。总计：{total}。下批约 {delay} 秒后...',
        magicSearchIndexingPaused: '索引完成（共 {total} 部作品）。正在监视新作品...',
        magicSearchBulkIndexFailed: '批量索引失败。',
        magicSearchRateLimitedRetry: '已限流。{wait} 秒后重试...',
        magicSearchTimeout: '搜索超时。请尝试更简单的查询。',
        magicSearchCancelled: '搜索已取消。',
        magicSearchCancel: '取消',

        // Advanced Search
        advSearch: '高级搜索',
        advSearchBtn: '高级搜索 / 播放列表生成器',
        advIncludeTags: '包含标签',
        advExcludeTags: '排除标签',
        advFilterTags: '输入以筛选标签...',
        advVoiceActor: '声优 (CV)',
        advSearchVA: '搜索声优...',
        advCircle: '社团',
        advSearchCircle: '搜索社团...',
        advDuration: '时长（分钟）',
        advSortBy: '排序方式',
        advMinRating: '最低评分',
        advMinPrice: '最低价格（¥）',
        advMinSales: '最低销量',
        advAgeRating: '年龄限制',
        advLanguage: '语言',
        advMinPlaceholder: '最小',
        advMaxPlaceholder: '最大',
        advMinDurationAria: '最短时长（分钟）',
        advMaxDurationAria: '最长时长（分钟）',
        advPresetShortTitle: '0-30 分钟',
        advPresetShortAria: '0 到 30 分钟',
        advPresetMediumTitle: '30-120 分钟',
        advPresetMediumAria: '30 到 120 分钟',
        advPresetLongTitle: '120+ 分钟',
        advPresetLongAria: '120 分钟以上',
        advSortDescAria: '降序',
        advSortAscAria: '升序',
        advMinRatingPlaceholder: '例如 4.0',
        advMinPricePlaceholder: '例如 500',
        advMinSalesPlaceholder: '例如 1000',
        advLangJa: '日语（日本語）',
        advLangEn: '英语',
        advLangKo: '韩语（한국어）',
        advLangZhCn: '简体中文',
        advLangZhTw: '繁體中文',
        advRemoveTag: '移除 {tag}',
        advRemoveVA: '移除声优 {name}',
        advRemoveCircle: '移除社团 {name}',
        advSearchAction: '搜索',
        advCreatePlaylist: '创建播放列表',
        advWorks: '作品数：',
        advDesc: '降序',
        advAsc: '升序',
        advShort: '短',
        advMedium: '中',
        advLong: '长',
        advAny: '任意',
        advAllAges: '全年齡',
        advAdult: '成人 (18+)',
        advNoResults: '未找到结果',
        advLoadingTags: '加载标签中...',
        advLoadingVA: '加载声优中...',
        advLoadingCircles: '加载社团中...',
        advSearching: '搜索中...',
        advFetching: '获取第 {page}/{max} 页...',
        advNoWorks: '未找到作品。',
        advFound: '找到 {count} 个作品。',
        advCancelled: '已取消。',
        advCreatingPlaylist: '创建播放列表中...',
        advPlaylistCreated: '播放列表已创建！正在跳转...',
        advPlaylistFailed: '创建播放列表失败。请查看控制台。',
        advSearchFailed: '搜索失败。请查看控制台。',
        advCancelling: '取消中...',
        advFindingWorks: '查找作品中...',
        advNoWorksPlaylist: '未找到可加入播放列表的作品。',
        advGoToWork: '前往作品',
        advPlaylistDesc: '从 {pool} 个候选作品中智能精选了 {count} 个作品。',
        advPlaylistParams: '筛选条件',

        // Sort options
        sortNewest: '加入时间',
        sortRelease: '发布时间',
        sortRating: '用户评分',
        sortDownloads: '销量排序',
        sortReviews: '评论数',
        sortPrice: '价格',
        sortDlsiteRating: '评价排序',
        sortNSFW: 'R18排序',
        sortRandom: '随机',
        sortRJCode: 'RJ号排序',

        // About & Links
        aboutHeader: '关于',
        readmeDocs: '文档与源代码',
        readmeDocsSub: '完整功能指南、架构文档和 GitHub 源代码',
        reportIssue: '报告问题',
        reportIssueSub: '发现 Bug 或有功能建议？在 GitHub 上提交 Issue',
        discordLabel: 'Discord',
        discordSub: '有问题、建议，或者想聊聊？添加我的 Discord：henry281199',
        discordCopy: '复制用户名',
        donateLabel: '支持开发',
        donateSub: '本项目由一位开发者在业余时间独立构建和维护——仅AI订阅费用就已超过300英镑，用于实现实时转录和翻译等功能。本项目永远免费。如果它改善了您的体验，一笔小小的捐赠将帮助分担这些成本并激励持续开发。',

        // Credits
        creditsHeader: '致谢与鸣谢',
        creditsSub: '站在巨人的肩膀上。特别感谢以下项目的开发者：',
        creditsAsmrOnline: '托管平台',
        creditsKikoeru: '核心媒体服务器和播放器',
        creditsCollections: '语义搜索灵感',
        creditsSubtitleTranslator: '原始字幕翻译脚本',
        creditsDLsite: '内容和元数据提供商',
        creditsYuro: '社区移动客户端',
        creditsTampermonkey: '提供 GM_* API 的用户脚本运行环境',
        creditsWhisper: '语音识别模型',
        creditsXenova: '浏览器推理用 ONNX 模型转换',
        creditsGoogleTranslate: '备用翻译服务',
        creditsTransformers: '浏览器端机器学习推理引擎',
        creditsONNXRuntime: '跨平台机器学习推理运行时',
        creditsHuggingFace: '机器学习模型托管与分发',
        creditsVue: '渐进式 JavaScript UI 框架',
        creditsQuasar: 'Vue UI 组件框架（宿主应用）',
        creditsPdfJs: 'PDF 渲染和文本提取',
        creditsIdb: '本地存储 IndexedDB 封装库',
        creditsFuseJs: '模糊搜索库',
        creditsVitePluginMonkey: '基于 Vite 的用户脚本构建工具',
        creditsMaterialIcons: '全站 UI 图标字体',
        creditsHVDB: '音声作品元数据交叉引用数据库',
        creditsChobit: '替代音声作品搜索引擎',
        creditsH2k: '翻译词汇表所用日语词频数据',

        // Metadata Panel
        metaShowDetails: '显示 DLsite 详情',
        metaHideDetails: '隐藏 DLsite 详情',
        metaRefresh: '刷新元数据',
        metaFileContents: '文件内容 ({count})',

        // Playlist Controls
        playlistPrevWork: '上一个作品',
        playlistNextWork: '下一个作品',
        playlistPublicTitle: '公共播放列表',
        playlistFindMore: '查找更多',
        playlistRandomize: '随机排序',
        playlistRandomizing: '正在打乱...',
        playlistFilterPlaceholder: '筛选播放列表...',
        playlistOnlineOnly: '仅在线',
        playlistLoadMore: '加载更多',
        playlistLoadingMore: '正在加载更多...',
        playlistLoadingDone: '已加载全部播放列表。',
        playlistLoadingUser: '正在获取您的播放列表...',
        playlistLoadStatus: '已加载 {loaded}/{total}',
        playlistLoadStatusDone: '已加载 {loaded}/{total}（完成）',
        playlistSearching: '正在通过 Google 搜索公共播放列表...',
        playlistSearchingPage: '正在搜索第 {page} 页... 已找到 {found} 个播放列表',
        playlistSearchingButton: '搜索中...',
        playlistSearchFailed: '搜索失败，请重试。',
        playlistDiscoverTitle: '发现公共播放列表',
        playlistDiscoverHint: '尚未发现公共播放列表。点击“{action}”以查找已索引的播放列表，或手动添加播放列表链接。',
        playlistLoadFailed: '加载公共播放列表失败，请稍后重试。',
        playlistAddPlaceholder: '粘贴播放列表链接或 ID...',
        playlistAddButton: '添加',
        playlistAddedBadge: '已添加',
        playlistFilterAll: '全部',
        playlistFilterMine: '我的',
        playlistFilterPublic: '仅公开',
        playlistsTitle: '播放列表',

        // Work Tree
        flatView: '平铺视图',
        fileListHeader: '全部文件',
        fileListCount: '{count} 个文件',
        fileListClose: '关闭文件列表',
        autoFilterFolders: '自动导航文件夹',
        autoFilterFoldersSub: '自动跳转到最佳内容文件夹',

        // Playback Speed
        speedTitle: '速度: {rate}x',

        // Learner Mode Overflow
        more: '更多',
        aiTranscribe: 'AI 自动转录',
        openWorkDetail: '打开作品详情',
        loadSubtitle: '加载本地字幕',
        downloadTrack: '下载音轨',

        // Whisper Status
        whisperLoading: '正在加载模型...',
        whisperTranscribing: '正在转录...',
        whisperTranslating: '正在翻译 {count} 个片段...',
        whisperError: 'AI 错误: {message}',
        whisperBtnLabel: 'AI 转录',
        whisperBtnTitle: '使用 Whisper AI 转录音频',
        whisperTranscriptDownload: 'LRC',
        whisperTranscriptDownloadLang: 'LRC（{lang}）',
        vttDownload: 'VTT',
        vttDownloadTranslated: 'VTT（翻译）',
        whisperHlsWarning: '检测到 HLS 流媒体——转录需要可下载的音频文件。',
        whisperStatus: '转录状态',
        whisperComplete: '转录完成',
        whisperReady: 'Whisper 已就绪',
        whisperChunkProgress: '正在转录… {current}秒 / {total}秒',
        whisperExistingSubs: '已有字幕。仍要转录吗？',
        whisperInit: '正在初始化...',
        whisperLoadingModelAudio: '加载模型并获取音频...',
        whisperFetchingAudio: '正在获取音频...',
        whisperDecodingAudio: '正在解码音频...',
        whisperWaitingForModel: '等待模型就绪...',
        whisperPreparingFirstChunk: '准备首个分段...',
        whisperStreamingAudio: '正在流式下载... {loaded}/{total} MB',
        whisperDownloadingAudio: '正在下载音频... {loaded}/{total} MB',
        whisperInitializingModel: '正在初始化模型（可能需要一些时间）...',
        whisperLoadingModelFile: '加载模型：{file}（{progress}%）',
        whisperLoadingFile: '加载中：{file}',
        whisperTranscribingElapsed: '正在转录... {elapsed}秒{segments}',
        whisperSegmentCount: ' · {count} 段',
        whisperFallbackModel: '模型加载失败，正在切换到 {model}...',
        whisperFallbackApplied: '已切换到 {model}（{reason}）',
        whisperForceWasm: 'WebGPU 失败，切换到 WASM...',
        whisperWarmupTimeout: '模型预热超时',
        whisperWarmupFailed: '模型预热失败',
        whisperWarmupFailedDetail: '模型预热失败：{message}',
        whisperWebGpuFallback: 'WebGPU 输出为空，正在改用 WASM...',
        whisperWebGpuRequired: '实时转录需要 WebGPU。',
        whisperNoAudioSource: '未找到音频源。请先播放一首音轨。',
        whisperFetchAudioFailed: '获取音频失败。请检查网络或 CORS。',
        whisperAudioCorrupted: '音频数据已损坏。请尝试其他文件。',
        whisperAudioProcessingFailed: '音频处理失败：{message}',
        whisperWorkerError: 'Worker 错误：{message}',
        whisperTranscriptionError: '转录错误：{message}',
        whisperRecovering: 'GPU 错误 — 正在使用 CPU 重启...',
        whisperGpuCrashed: 'GPU 崩溃 — 请刷新页面。如果问题仍然存在，请重启浏览器。',
        whisperUnknownError: '未知错误',

        // WorkTreeCopy
        copyBtn: '复制',
        copiedNotify: '已复制：{text}',

        // Comment Section
        commentsHeader: '听众社区',
        commentsMyReview: '分享你的感受',
        commentsDLsite: '来自 DLsite 的评价',
        commentsPlaceholder: '演出效果如何？快来分享你的想法吧...',
        commentsSaving: '保存中...',
        commentsSaved: '已保存',
        commentsSaveFailed: '保存失败',
        commentsTranslate: '翻译',
        commentsShowOriginal: '显示原文',
        commentsLoading: '加载评论中...',
        commentsNoReviews: '未找到评论',
        commentsDelete: '删除我的评论',
        commentsDeleteConfirm: '删除此作品的评价？',
        commentsCount: '{count} 条评论',
        commentsExpand: '显示评论',
        commentsCollapse: '隐藏评论',
        commentsFetchFailed: '无法获取 DLsite 评论。请检查设置中的代理 URL。',

        // Media Viewer
        mediaViewerPdfLoadFailed: 'PDF 加载失败',
        mediaViewerTextLoadFailed: '文本文件加载失败',
        mediaViewerTextTruncated: '预览已限制为 {count} KB',

        // SFW Mode
        sfwMode: '安全模式',
        sfwModeSub: '隐藏所有图片和缩略图，适合公开场合使用',

        // Translation Toggle
        translateMode: '翻译',
        translateModeSub: '翻译标签、标题和界面元素（需要重新加载）',
        translateCnToJp: '中文 → 日本語',
        translateCnToJpSub: '无论翻译开关状态，均将中文文本静默替换为日语',

        // Feature Toggles (Global)
        featureToggles: '功能开关',
        enablePlaylistDiscovery: '播放列表发现',
        enablePlaylistDiscoverySub: '通过 Google 搜索查找共享播放列表',
        enableLearnerMode: '学习模式',
        enableLearnerModeSub: '双语字幕和学习控制',
        learnerBlurLabel: '模糊翻译',
        learnerBlurSub: '默认模糊翻译（悬停或点击显示）',
        karaokeMode: '卡拉OK模式',
        karaokeModeSub: '以强调色高亮当前播放的单词',
        segmentMode: '整句模式',
        segmentModeSub: '显示未播放的文字（变暗）而非隐藏',
        enableAdvancedSearch: '高级搜索',
        enableAdvancedSearchSub: '按标签、声优、社团、时长筛选',
        enableWorkMetadata: '增强元数据',
        enableWorkMetadataSub: '显示扩展元数据和 DLsite 信息',
        enablePlayerTranslator: '播放器翻译',
        enablePlayerTranslatorSub: '翻译播放器界面',
        enableSupportButton: '支持按钮',
        enableSupportButtonSub: '显示支持/反馈链接',
        enableWorkTreeManager: '文件夹导航 & 平铺视图',
        enableWorkTreeManagerSub: '自动文件夹导航和平铺视图',
        enableTagFilters: '标签过滤器',
        enableTagFiltersSub: '隐藏特定标签的作品',
        enableVectorSearch: '语义搜索',
        enableVectorSearchSub: 'AI 驱动的搜索——首次索引可能需要约一天',
        enableWhisper: 'Whisper',
        enableWhisperSub: '本地 AI 转录',
        alwaysTranscribe: '自动转录',
        alwaysTranscribeSub: '新曲目播放时自动开始转录',
        forceWhisperWasm: '强制 CPU 模式（WASM）',
        forceWhisperWasmSub: '为 Whisper 禁用 WebGPU，改用 CPU 以提升弱显卡兼容性',
        enableFavicon: '动态图标',
        enableFaviconSub: '在标签页显示封面',
        enableMediaSession: '媒体会话',
        enableMediaSessionSub: '系统媒体控制支持',
        enableMenuIconFixer: '菜单图标修复',
        enableMenuIconFixerSub: '修复侧边栏缺失的图标',
        enableStoreBackup: '存储备份',
        enableStoreBackupSub: '备份/恢复插件数据',
        enableHVDBLink: 'HVDB 链接',
        enableHVDBLinkSub: '链接到 HVDB 元数据',
        enableInterfaceTranslator: '界面翻译',
        enableInterfaceTranslatorSub: '翻译 UI 元素',
        enablePageTitleManager: '页面标题管理',
        enablePageTitleManagerSub: '修复标签页标题显示',
        enableKeyboardManager: '键盘快捷键',
        enableKeyboardManagerSub: '自定义热键',
        enableRouteStateSync: '路由状态同步',
        enableRouteStateSyncSub: '与 URL 同步应用状态',
        enableMediaViewer: '媒体查看器',
        enableMediaViewerSub: '在灯箱中预览图片/视频',
        enablePlayerFullscreen: '全屏播放器',
        enablePlayerFullscreenSub: '展开播放器的全屏切换',
        enablePlayerGallery: '播放器图库',
        enablePlayerGallerySub: '在播放器封面区域浏览作品图片',
        fullscreenToggle: '全屏',
        fullscreenExit: '退出全屏',
        galleryPrev: '上一张',
        galleryNext: '下一张',
        galleryExclude: '隐藏此图片',
        gallerySlideshowPause: '暂停幻灯片',
        gallerySlideshowResume: '继续幻灯片',
        galleryAutoSlideshow: '自动幻灯片',
        galleryAutoSlideshowSub: '在全屏和灯箱模式下自动循环浏览图片',
        galleryAutoSlideshowInterval: '幻灯片间隔',
        galleryAutoSlideshowIntervalSub: '图片切换间隔秒数',
        keyboardShortcuts: '键盘快捷键',
        hotkeyPlayPause: '播放 / 暂停',
        hotkeyMute: '静音',
        hotkeyFullscreen: '全屏',
        hotkeySeekBack: '后退 (5秒)',
        hotkeySeekForward: '前进 (5秒)',
        hotkeySeekBackLong: '后退 (10秒)',
        hotkeySeekForwardLong: '前进 (10秒)',
        hotkeyVolumeUp: '音量增大',
        hotkeyVolumeDown: '音量减小',
        hotkeyPrevLine: '上一行 / 轨道',
        hotkeyNextLine: '下一行 / 轨道',
        hotkeyPrevTrack: '上一曲',
        hotkeyNextTrack: '下一曲',
        hotkeySpeedUp: '加速',
        hotkeySpeedDown: '减速',
        hotkeyToggleBlur: '切换模糊',
        revealTranslation: '显示翻译',
        hideTranslation: '隐藏翻译',
        hotkeyToggleJP: '切换日语',
        hotkeySpeedReset: '重置速度',
        hotkeyGalleryExclude: '隐藏图片 (图库)',
        hotkeyGalleryPrev: '图库上一张',
        hotkeyGalleryNext: '图库下一张',
        hotkeyPressKey: '按下按键…',
        hotkeyReset: '重置为默认',
        enableWorkTreeCopy: '复制按钮',
        enableWorkTreeCopySub: '在文件资源管理器中复制文件名',
        enableCommentSection: '评论区',
        enableCommentSectionSub: '显示 DLsite 评论',
        enableInfiniteScroll: '无限滚动',
        enableInfiniteScrollSub: '滚动时自动加载更多内容',
        infScrollEndOfResults: '已到底部',
        infScrollRateLimitRetry: '请求频率受限，{seconds}秒后重试...',
        infScrollRateLimitError: '请求频率受限，请稍候再滚动。',
        infScrollLoadingImages: '正在加载 {count} 张图片...',
        infScrollSales: '销量: {count}',
        infScrollAllAges: '全年龄',

        // JOI Tool
        enableJoiTool: 'JOI 工具',
        enableJoiToolSub: '与实时转录同步的互动边缘游戏',
        alwaysShowJoi: '始终显示 JOI',
        alwaysShowJoiSub: '播放音频时自动激活 JOI 工具',
        joiTool: 'JOI 工具',
        joiToggle: '切换 JOI',
        joiGo: '继续',
        joiStop: '停止',
        joiEdge: '边缘',
        joiCum: '释放',
        joiDenied: '拒绝',
        joiRuined: '失败',
        joiIdle: '就绪',
        joiGoSlow: '慢慢来...',
        joiGoFast: '加快速度...',
        joiGoGentle: '轻柔地...',
        joiStopHands: '停下！',
        joiStopWait: '等一下...',
        joiStopBreathe: '深呼吸...',
        joiEdgeClose: '就在边缘...',
        joiEdgeHold: '保持住...',
        joiEdgeDanger: '小心...',
        joiCumNow: '现在！',
        joiDeniedMsg: '这次不行。',
        joiRuinedMsg: '太迟了...',
        joiResuming: '{sec}秒后继续...',
        joiNoWhisper: '请先启用 Whisper',
        joiActivated: 'JOI 已激活',
        joiDeactivated: 'JOI 已停用',

        // Visualizer
        enableVisualizer: '声音可视化',
        enableVisualizerSub: '实时音频频率可视化条',
        alwaysShowVisualizer: '始终显示可视化',
        alwaysShowVisualizerSub: '播放音频时自动激活可视化',
        vizToggle: '切换可视化',

        // Visit Counter
        enableVisitCounter: '访问计数',
        enableVisitCounterSub: '显示你打开每个作品的次数',

        // Continue Listening
        enableContinueListening: '继续收听',
        enableContinueListeningSub: '在首页显示状态为"在听"的作品',
        continueListeningTitle: '继续收听',

        // JPDB Integration
        jpdbSection: 'JPDB 集成',
        enableJpdb: '启用 JPDB',
        enableJpdbSub: '通过 jpdb.io 提供注音、声调和词汇追踪',
        jpdbApiToken: 'API 密钥',
        jpdbApiTokenSub: '需要免费账户 — 从 jpdb.io 设置页复制',
        jpdbApiTokenPlaceholder: '粘贴你的 jpdb.io API 密钥',
        jpdbGetApiKey: '从 jpdb.io 获取 API 密钥',
        jpdbShowFurigana: '显示注音',
        jpdbShowFuriganaSub: '在汉字上方显示假名注音',
        jpdbShowPitchAccent: '声调标记',
        jpdbShowPitchAccentSub: '显示单词的声调模式（会覆盖词汇状态下划线）',
        jpdbSiteFurigana: '全站注音',
        jpdbSiteFuriganaSub: '为标题、标签和页面内容添加注音',
        jpdbSubtitleFurigana: '字幕注音',
        jpdbSubtitleFuriganaSub: '在学习模式的字幕中添加注音',
        jpdbPitchStyle: '声调样式',
        jpdbPitchStyleSub: '声调标记的显示方式',
        jpdbPitchUnderline: '下划线',
        jpdbPitchColor: '颜色',
        jpdbPitchBoth: '两者',
        jpdbPitchOff: '关闭',
        hotkeyJpdbPopover: '词语弹窗',
        jpdbMiningDeck: '采集牌组',
        jpdbMiningDeckSub: '采集的单词添加到此牌组（留空使用 FORQ）',
        jpdbMiningDeckPlaceholder: 'forq',
        jpdbAddToForq: '添加到 FORQ',
        jpdbAddToForqSub: '采集时同时添加到 FORQ 牌组',
        jpdbDisableReviews: '禁用复习',
        jpdbDisableReviewsSub: '隐藏弹窗中的复习评分按钮',
        jpdbUseTwoGrades: '两级评分',
        jpdbUseTwoGradesSub: '使用 不会/会 代替五级评分',
        jpdbNeverForgetDeck: '永记牌组',
        jpdbNeverForgetDeckSub: '永记单词的牌组 ID',
        jpdbBlacklistDeck: '屏蔽牌组',
        jpdbBlacklistDeckSub: '屏蔽单词的牌组 ID',
        jpdbPopoverNoKey: '设置 jpdb.io API 密钥以追踪词汇',
        jpdbPopoverGetKey: '获取密钥',
        jpdbPopoverRank: '频率',
        jpdbPopoverState: '状态',
        jpdbBtnAdd: '添加',
        jpdbBtnNeverForget: '永记',
        jpdbBtnForget: '取消永记',
        jpdbBtnBlacklist: '屏蔽',
        jpdbBtnUnlist: '取消屏蔽',
        jpdbGradeNothing: '不认识',
        jpdbGradeSomething: '有印象',
        jpdbGradeHard: '困难',
        jpdbGradeOkay: '一般',
        jpdbGradeEasy: '简单',
        jpdbGradeFail: '不会',
        jpdbGradePass: '会',
        jpdbStateNew: '新词',
        jpdbStateLearning: '学习中',
        jpdbStateKnown: '已掌握',
        jpdbStateDue: '待复习',
        jpdbStateFailed: '未通过',
        jpdbStateLocked: '已锁定',
        jpdbStateNotInDeck: '未加入',
        jpdbStateSuspended: '已暂停',
        jpdbStateBlacklisted: '已屏蔽',
        jpdbStateNeverForget: '永记',
        jpdbStateRedundant: '冗余',
        jpdbCredits: '注音与词汇功能由 jpdb.io 提供',
        jpdbCreditsReader: '基于 chinokusari 的 anki-jpdb.reader',
    },
    ja: {
        // Settings - Radio
        radioMode: 'ラジオモード',
        off: 'オフ',
        on: 'オン',
        radioStatusIdle: '待機中',
        radioStatusStarting: '再生を開始しています...',
        radioStatusLoading: '作品を読み込み中...',
        radioStatusSkipping: '次の作品へスキップ中...',
        radioStatusPlaying: '再生中',
        radioSettings: 'ラジオ設定',
        playlistSettings: 'プレイリスト設定',
        playAll: '作品全体を再生',
        playAllSub: 'キュー内の全トラックを再生してから次の作品に進む',
        radioFlatTracks: 'トラックプール: 全フォルダ',
        radioFlatTracksSub: '単一フォルダではなく、作品ツリー全体の音声を対象にする',
        trackPoolAllFolders: 'トラックプール: 全フォルダ',
        trackPoolAllFoldersSub: '作品ツリー内の全音声からキューを作成。作品全体再生がオフの場合は、このプールから1曲だけ再生します。',
        folderPoolSettings: 'フォルダ/トラックプール設定',
        shuffle: 'シャッフル',
        shuffleSub: '再生順をランダムにする',
        loopPlaylist: 'ループ',
        loopPlaylistSub: 'プレイリスト終了後に最初から再開する',
        prefFormat: '優先フォーマット',
        prefFormatSub: '例: wav, mp3',
        sePref: 'SE 優先',
        sePrefSub: '効果音フォルダを優先する',
        bgmPref: 'BGM 優先',
        bgmPrefSub: 'BGM付きフォルダを優先する',
        primaryLang: '主字幕言語',
        primaryLangSub: '主字幕の言語コード (例: ja, en)',
        targetLang: '副字幕言語',
        targetLangSub: '副字幕の言語コード (例: en, es)',
        liveCaptionTitle: 'ヒント: ライブキャプション',
        liveCaptionMsg: 'システムのライブキャプション機能を有効にしてみてください！',
        prevLine: '前の行',
        nextLine: '次の行',
        toggleJP: '日本語表示切替',
        autoProgress: 'ステータストラッキング',
        autoProgressSub: '再生状況に応じて作品ステータスを自動更新',
        autoProgressSection: 'ステータス自動化',
        autoProgressMarked: '訪問でマーク',
        autoProgressMarkedDesc: '作品ページを訪問すると「気になる」にする',
        autoProgressListening: '再生でマーク',
        autoProgressListeningDesc: '5秒以上再生すると「聴いている」にする',
        autoProgressListened: '完了でマーク',
        autoProgressListenedDesc: '最後のトラックが85%に達すると「聴いた」にする',
        autoProgressReplay: 'リプレイ追跡',
        autoProgressReplayDesc: '複数回の完全再生後に「リプレイ」にする',
        autoProgressPostponed: '延期マーク',
        autoProgressPostponedDesc: 'トラックの30%未満しか再生せず離れると「延期」にする',
        autoProgressReplayThreshold: 'リプレイ回数',
        autoProgressReplayThresholdDesc: '何回完全再生したらリプレイとみなすか',
        autoProgressRadioSkipThreshold: '延期訪問上限',
        autoProgressRadioSkipThresholdDesc: '未視聴の訪問回数がこの値に達したら「延期」にする',

        // Settings - Whisper
        embeddingModelReady: '埋め込みモデルの準備ができました。',
        embeddingLoading: '埋め込みモデルを読み込み中...',
        embeddingLoadingFile: '埋め込みモデル読込: {file}',
        clearTranslationCache: '翻訳キャッシュをクリア',
        clearTranslationCacheSub: 'キャッシュされた翻訳をすべて削除して再翻訳を強制',
        clearTranslationCacheConfirm: 'キャッシュされた翻訳をすべてクリアしますか？',
        clearTranslationCacheSuccess: '{count} 件のキャッシュされた翻訳をクリアしました。',
        downloadWhisperModel: 'Whisper モデルをダウンロード',
        downloadWhisperModelSub: '初回使用時の遅延を避けるため Whisper モデルを事前ロード',
        downloadWhisperModelReady: 'Whisper モデルの準備ができました。',
        downloadWhisperModelFailed: 'Whisper モデルのダウンロードに失敗しました: {message}',
        downloadWhisperModelLoading: 'Whisper モデルをダウンロード中',
        whisperSettings: 'Whisper 設定',
        translationSettings: '翻訳設定',

        // Settings - Storage
        storageData: 'ストレージとデータ',
        factoryReset: '初期化',
        factoryResetSub: 'すべてのキャッシュデータ、設定、データベースを削除',
        factoryResetConfirm: 'すべてのプラグインデータ（音声キャッシュ、ベクトルインデックス、タグ翻訳、設定）が削除されます。続行しますか？',
        factoryResetConfirm2: '本当によろしいですか？この操作は取り消せません。',
        factoryResetting: 'リセット中...',
        backupSettings: '設定バックアップ',
        backupSettingsSub: 'リセット前に現在の設定をJSONとしてダウンロード',
        restoreSettings: '設定復元',
        restoreSettingsSub: '以前保存したJSONバックアップをアップロード',
        restoreSuccess: '{count} 件の設定を復元しました。リロード中...',
        restoreFailed: '設定の復元に失敗しました。有効なJSONファイルですか？',
        generalSettings: '一般設定',
        enableLogging: 'コンソールログ有効化',
        enableLoggingSub: '技術情報をコンソールに出力（デバッグ推奨）',

        // DLsite Proxy
        dlsiteProxy: 'DLsite プロキシ',
        dlsiteProxySub: '地域制限を回避するための Cloudflare Worker プロキシ URL',
        dlsiteProxySetup: '構築ガイド',

        // API Server
        apiServer: 'API サーバー',
        apiServerSub: 'ASMR.one API サーバー (ミラー) を選択',
        dlsiteProxyUrl: 'プロキシ URL',
        dlsiteProxyUrlSub: '日本国外で制限されているDLsiteのコメントや情報を表示します。設定は無料で簡単です。',
        dlsiteProxyUrlSetup: '詳細セットアップガイドを表示',
        dlsiteProxyFullGuide: '<h4>Cloudflare プロキシセットアップガイド</h4>' +
            '<p>1. <a href="https://dash.cloudflare.com/" target="_blank" class="text-primary asmr-settings-link">Cloudflare ダッシュボード</a>にログインします。</p>' +
            '<p>2. <b>Compute & AI</b> > <b>Workers & Pages</b> に移動し、<b>Create</b> をクリックします。</p>' +
            '<p>3. 名称を <code>dlsite-proxy</code> にして <b>Deploy</b> をクリックします。</p>' +
            '<p>4. <b>Edit Code</b> をクリックし、デフォルトのコードを削除して下のコードを貼り付けます。</p>' +
            '<p>5. 右上の <b>Deploy</b> をクリックします。</p>' +
            '<p>6. <b>Settings</b> > <b>General</b> > <b>Placement</b> に移動し、<b>Region</b> を選択。プロバイダーを <b>Microsoft Azure</b> に、リージョンを <b>japaneast</b> に設定します。</p>' +
            '<p>7. WorkerのURLをコピーして、ここのプロキシURLフィールドに貼り付けます。</p>',
        dlsiteProxyWorkerCode: 'Worker プロキシコード',
        copyCode: 'コードをコピー',
        copied: 'コピーしました！',

        // Semantic Search (VectorSearch)
        magicSearch: 'セマンティック検索',
        magicSearchBtn: 'セマンティック検索',
        magicSearchPlaceholder: "機能を記述 (例: '純粋な耳かき')...",
        magicSearchGo: '検索',
        magicSearchPrev: '前へ',
        magicSearchNext: '次へ',
        magicSearchReady: '準備完了',
        magicSearchSearching: '検索中...',
        magicSearchSearchingJP: '検索中（日本語翻訳適用）...',
        magicSearchPreparing: '検索準備中...',
        magicSearchNoMatches: '一致するものが見つかりません。',
        magicSearchNoRelevantMatches: '関連する結果が見つかりません。別の検索キーワードをお試しください。',
        magicSearchWorksIndexed: '{count} 作品をインデックス済み',
        magicSearchMatch: '% 一致',
        magicSearchPage: 'ページ {current} / {total}',
        magicSearchShowing: '{start}-{end} / {total} 件表示',
        magicSearchEmbedFail: '埋め込みの生成に失敗しました。コンソールのエラーを確認してください。',
        magicSearchIndexEmpty: 'インデックスが空です。最近の作品を自動インデックス中...',
        magicSearchIndexEmptyCheck: 'インデックスがまだ空です。コンソールのエラーを確認してください。',
        magicSearchCooldown: 'システムクールダウン中（+{wait}秒）。お待ちください...',
        magicSearchFetchingLatest: '最新の作品を取得中...',
        magicSearchFetchingPage: 'ページ {page}/{end} を取得中...',
        magicSearchWorksRateLimited: 'Works API がレート制限されました。後で再試行します...',
        magicSearchIndexingPage: 'ページ {page} をインデックス中（{count} 作品）...',
        magicSearchIndexingContinue: '{indexed} 作品をインデックス済み（次はページ {cursor}）。合計：{total}。次のバッチまで約 {delay} 秒...',
        magicSearchIndexingPaused: 'インデックス完了（{total} 作品）。新着を監視中...',
        magicSearchBulkIndexFailed: '一括インデックスに失敗しました。',
        magicSearchRateLimitedRetry: 'レート制限中。{wait} 秒後に再試行...',
        magicSearchTimeout: '検索がタイムアウトしました。より簡単なクエリをお試しください。',
        magicSearchCancelled: '検索がキャンセルされました。',
        magicSearchCancel: 'キャンセル',

        // Advanced Search
        advSearch: '詳細検索',
        advSearchBtn: '詳細検索 / プレイリスト作成',
        advIncludeTags: 'タグを含む',
        advExcludeTags: 'タグを除外',
        advFilterTags: 'タグで絞り込み...',
        advVoiceActor: '声優 (CV)',
        advSearchVA: '声優を検索...',
        advCircle: 'サークル',
        advSearchCircle: 'サークルを検索...',
        advDuration: '再生時間（分）',
        advSortBy: '並び替え',
        advMinRating: '最低評価',
        advMinPrice: '最低価格（¥）',
        advMinSales: '最低販売数',
        advAgeRating: '年齢制限',
        advLanguage: '言語',
        advMinPlaceholder: '最小',
        advMaxPlaceholder: '最大',
        advMinDurationAria: '最短再生時間（分）',
        advMaxDurationAria: '最長再生時間（分）',
        advPresetShortTitle: '0-30 分',
        advPresetShortAria: '0～30 分',
        advPresetMediumTitle: '30-120 分',
        advPresetMediumAria: '30～120 分',
        advPresetLongTitle: '120 分以上',
        advPresetLongAria: '120 分以上',
        advSortDescAria: '降順',
        advSortAscAria: '昇順',
        advMinRatingPlaceholder: '例: 4.0',
        advMinPricePlaceholder: '例: 500',
        advMinSalesPlaceholder: '例: 1000',
        advLangJa: '日本語',
        advLangEn: '英語',
        advLangKo: '韓国語（한국어）',
        advLangZhCn: '簡体中文',
        advLangZhTw: '繁體中文',
        advRemoveTag: '{tag} を削除',
        advRemoveVA: '声優 {name} を削除',
        advRemoveCircle: 'サークル {name} を削除',
        advSearchAction: '検索',
        advCreatePlaylist: 'プレイリスト作成',
        advWorks: '作品数:',
        advDesc: '降順',
        advAsc: '昇順',
        advShort: '短い',
        advMedium: '中',
        advLong: '長い',
        advAny: '全て',
        advAllAges: '全年齢',
        advAdult: '成人向け (18+)',
        advNoResults: '結果が見つかりません',
        advLoadingTags: 'タグ読込中...',
        advLoadingVA: '声優読込中...',
        advLoadingCircles: 'サークル読込中...',
        advSearching: '検索中...',
        advFetching: 'ページ {page}/{max} 取得中...',
        advNoWorks: '作品が見つかりません。',
        advFound: '{count} 件の作品が見つかりました。',
        advCancelled: 'キャンセルしました。',
        advCreatingPlaylist: 'プレイリスト作成中...',
        advPlaylistCreated: 'プレイリスト作成完了！リダイレクト中...',
        advPlaylistFailed: 'プレイリスト作成に失敗しました。コンソールを確認してください。',
        advSearchFailed: '検索に失敗しました。コンソールを確認してください。',
        advCancelling: 'キャンセル中...',
        advFindingWorks: '作品を検索中...',
        advNoWorksPlaylist: 'プレイリストに追加する作品が見つかりません。',
        advGoToWork: '作品を見る',
        advPlaylistDesc: '候補 {pool} 作品の中から {count} 作品をスマートに選出しました。',
        advPlaylistParams: 'フィルター',

        // Sort options
        sortNewest: '最新',
        sortRelease: 'リリース日',
        sortRating: 'ユーザー評価',
        sortDownloads: 'ダウンロード数',
        sortReviews: 'レビュー数',
        sortPrice: '価格',
        sortDlsiteRating: 'DLsite 評価',
        sortNSFW: 'R18',
        sortRandom: 'ランダム',
        sortRJCode: 'RJ コード',

        // About & Links
        aboutHeader: '概要',
        readmeDocs: 'ドキュメントとソースコード',
        readmeDocsSub: '機能ガイド、アーキテクチャドキュメント、GitHubソースコード',
        reportIssue: '問題を報告',
        reportIssueSub: 'バグや機能リクエストがありますか？GitHubでIssueを作成してください',
        discordLabel: 'Discord',
        discordSub: '質問・提案・雑談など、お気軽にどうぞ。Discord: henry281199',
        discordCopy: 'ユーザー名をコピー',
        donateLabel: '開発を支援',
        donateSub: 'このプロジェクトは一人の開発者が空き時間に構築・保守しています。リアルタイム文字起こしや翻訳機能の実現だけでもAIサブスク費用が300ポンド以上かかっています。永久に無料ですが、もし役に立ったなら、寄付がこれらの費用を支え、開発継続の大きな励みになります。',

        // Credits
        creditsHeader: 'クレジットと謝辞',
        creditsSub: '巨人の肩の上に立って。これらのプロジェクトとクリエイターに感謝します：',
        creditsAsmrOnline: 'ホストプラットフォーム',
        creditsKikoeru: 'コアメディアサーバーとプレイヤー',
        creditsCollections: 'セマンティック検索のインスピレーション',
        creditsSubtitleTranslator: 'オリジナル字幕翻訳スクリプト',
        creditsDLsite: 'コンテンツとメタデータプロバイダー',
        creditsYuro: 'コミュニティモバイルクライアント',
        creditsTampermonkey: 'GM_* APIを提供するユーザースクリプト実行環境',
        creditsWhisper: '音声認識モデル',
        creditsXenova: 'ブラウザ推論用ONNXモデル変換',
        creditsGoogleTranslate: 'フォールバック翻訳サービス',
        creditsTransformers: 'ブラウザベースのML推論エンジン',
        creditsONNXRuntime: 'クロスプラットフォームML推論ランタイム',
        creditsHuggingFace: 'MLモデルのホスティングと配信',
        creditsVue: 'プログレッシブJavaScript UIフレームワーク',
        creditsQuasar: 'Vue UIコンポーネントフレームワーク（ホストアプリ）',
        creditsPdfJs: 'PDFレンダリングとテキスト抽出',
        creditsIdb: 'ローカルストレージ用IndexedDBラッパー',
        creditsFuseJs: 'ファジー検索ライブラリ',
        creditsVitePluginMonkey: 'Viteベースのユーザースクリプトビルドツール',
        creditsMaterialIcons: 'UI全体で使用されるアイコンフォント',
        creditsHVDB: '音声作品メタデータ相互参照データベース',
        creditsChobit: '代替音声作品検索エンジン',
        creditsH2k: '翻訳用語集の日本語頻度データ',

        // Metadata Panel
        metaShowDetails: 'DLsite 詳細を表示',
        metaHideDetails: 'DLsite 詳細を非表示',
        metaRefresh: 'メタデータを更新',
        metaFileContents: 'ファイル内容 ({count})',

        // Playlist Controls
        playlistPrevWork: '前の作品',
        playlistNextWork: '次の作品',
        playlistPublicTitle: '公開プレイリスト',
        playlistFindMore: 'さらに探す',
        playlistRandomize: 'ランダム',
        playlistRandomizing: 'シャッフル中...',
        playlistFilterPlaceholder: 'プレイリストを検索...',
        playlistOnlineOnly: 'オンラインのみ',
        playlistLoadMore: 'さらに読み込む',
        playlistLoadingMore: '読み込み中...',
        playlistLoadingDone: 'すべてのプレイリストを読み込みました。',
        playlistLoadingUser: 'プレイリストを取得中...',
        playlistLoadStatus: '{loaded}/{total} 件読み込み済み',
        playlistLoadStatusDone: '{loaded}/{total} 件（完了）',
        playlistSearching: 'Google で公開プレイリストを検索中...',
        playlistSearchingPage: '{page} ページ目を検索中... {found} 件見つかりました',
        playlistSearchingButton: '検索中...',
        playlistSearchFailed: '検索に失敗しました。もう一度お試しください。',
        playlistDiscoverTitle: '公開プレイリストを探す',
        playlistDiscoverHint: '公開プレイリストがまだ見つかりません。「{action}」をクリックして検索するか、プレイリスト URL を手動で追加してください。',
        playlistLoadFailed: '公開プレイリストの読み込みに失敗しました。しばらくしてから再試行してください。',
        playlistAddPlaceholder: 'プレイリストのURLまたはIDを貼り付け...',
        playlistAddButton: '追加',
        playlistAddedBadge: '追加済み',
        playlistFilterAll: 'すべて',
        playlistFilterMine: '自分の',
        playlistFilterPublic: '公開のみ',
        playlistsTitle: 'プレイリスト',

        // Work Tree
        flatView: 'フラット表示',
        fileListHeader: '全ファイル',
        fileListCount: '{count} ファイル',
        fileListClose: 'ファイルリストを閉じる',
        autoFilterFolders: 'フォルダ自動ナビ',
        autoFilterFoldersSub: '最適なコンテンツフォルダに自動移動',

        // Playback Speed
        speedTitle: '速度: {rate}x',

        // Learner Mode Overflow
        more: 'もっと見る',
        aiTranscribe: 'AI自動文字起こし',
        openWorkDetail: '作品詳細を開く',
        loadSubtitle: 'ローカル字幕を読み込む',
        downloadTrack: 'トラックをダウンロード',

        // Whisper Status
        whisperLoading: 'モデルを読み込み中...',
        whisperTranscribing: '文字起こし中...',
        whisperTranslating: '{count}セグメント翻訳中...',
        whisperError: 'AIエラー: {message}',
        whisperBtnLabel: 'AI文字起こし',
        whisperBtnTitle: 'Whisper AIで音声を文字起こし',
        whisperTranscriptDownload: 'LRC',
        whisperTranscriptDownloadLang: 'LRC（{lang}）',
        vttDownload: 'VTT',
        vttDownloadTranslated: 'VTT（翻訳済み）',
        whisperHlsWarning: 'HLSストリーミングを検出しました。文字起こしにはダウンロード可能な音声ファイルが必要です。',
        whisperStatus: '文字起こし状態',
        whisperComplete: '文字起こし完了',
        whisperReady: 'Whisper 準備完了',
        whisperChunkProgress: '文字起こし中… {current}秒 / {total}秒',
        whisperExistingSubs: '字幕は既にあります。それでも文字起こしますか？',
        whisperInit: '初期化中...',
        whisperLoadingModelAudio: 'モデルを読み込み中 + 音声取得中...',
        whisperFetchingAudio: '音声を取得中...',
        whisperDecodingAudio: '音声をデコード中...',
        whisperWaitingForModel: 'モデルを待機中...',
        whisperPreparingFirstChunk: '最初のチャンクを準備中...',
        whisperStreamingAudio: 'ストリーミング中... {loaded}/{total} MB',
        whisperDownloadingAudio: '音声をダウンロード中... {loaded}/{total} MB',
        whisperInitializingModel: 'モデルを初期化中（少し時間がかかる場合があります）...',
        whisperLoadingModelFile: 'モデル読込: {file}（{progress}%）',
        whisperLoadingFile: '読み込み中: {file}',
        whisperTranscribingElapsed: '文字起こし中... {elapsed}秒{segments}',
        whisperSegmentCount: ' · {count} セグメント',
        whisperFallbackModel: 'モデル読み込みに失敗しました。{model} に切り替えています...',
        whisperFallbackApplied: '{model} に切り替えました（{reason}）',
        whisperForceWasm: 'WebGPU に失敗しました。WASM に切り替えています...',
        whisperWarmupTimeout: 'モデルのウォームアップがタイムアウトしました',
        whisperWarmupFailed: 'モデルのウォームアップに失敗しました',
        whisperWarmupFailedDetail: 'モデルのウォームアップに失敗しました: {message}',
        whisperWebGpuFallback: 'WebGPU が空結果を返しました。WASM で再試行します...',
        whisperWebGpuRequired: 'ライブ文字起こしには WebGPU が必要です。',
        whisperNoAudioSource: '音声ソースが見つかりません。まずトラックを再生してください。',
        whisperFetchAudioFailed: '音声の取得に失敗しました。ネットワークまたは CORS を確認してください。',
        whisperAudioCorrupted: '音声データが破損しています。別のファイルを試してください。',
        whisperAudioProcessingFailed: '音声処理に失敗しました: {message}',
        whisperWorkerError: 'Worker エラー: {message}',
        whisperTranscriptionError: '文字起こしエラー: {message}',
        whisperRecovering: 'GPU エラー — CPU で再起動中...',
        whisperGpuCrashed: 'GPU がクラッシュしました — ページを更新してください。改善しない場合はブラウザを再起動してください。',
        whisperUnknownError: '不明なエラー',

        // WorkTreeCopy
        copyBtn: 'コピー',
        copiedNotify: 'コピー済み：{text}',

        // Comment Section
        commentsHeader: 'リスナーコミュニティ',
        commentsMyReview: '感想を共有する',
        commentsDLsite: 'DLsite のレビュー',
        commentsPlaceholder: '作品はいかがでしたか？あなたの感想をみんなに教えましょう...',
        commentsSaving: '保存中...',
        commentsSaved: '保存済み',
        commentsSaveFailed: '保存に失敗',
        commentsTranslate: '翻訳',
        commentsShowOriginal: '原文を表示',
        commentsLoading: 'レビュー読込中...',
        commentsNoReviews: 'レビューが見つかりません',
        commentsDelete: '自分のレビューを削除',
        commentsDeleteConfirm: 'この作品のレビューを削除しますか？',
        commentsCount: '{count} 件のレビュー',
        commentsExpand: 'レビューを表示',
        commentsCollapse: 'レビューを非表示',
        commentsFetchFailed: 'DLsite レビューの取得に失敗しました。設定のプロキシ URL を確認してください。',

        // Media Viewer
        mediaViewerPdfLoadFailed: 'PDF の読み込みに失敗しました',
        mediaViewerTextLoadFailed: 'テキストファイルの読み込みに失敗しました',
        mediaViewerTextTruncated: 'プレビューは {count} KB まで',

        // SFW Mode
        sfwMode: 'SFW モード',
        sfwModeSub: 'すべての画像とサムネイルを非表示にします（公共の場向け）',

        // Translation Toggle
        translateMode: '翻訳',
        translateModeSub: 'タグ、タイトル、UI要素を翻訳する（リロードが必要）',
        translateCnToJp: '中国語 → 日本語',
        translateCnToJpSub: '翻訳のオン/オフに関係なく中国語テキストを日本語に置換',

        // Feature Toggles (Global)
        featureToggles: '機能切り替え',
        enablePlaylistDiscovery: 'プレイリスト発見',
        enablePlaylistDiscoverySub: 'Google 検索で共有プレイリストを探す',
        enableLearnerMode: '学習モード',
        enableLearnerModeSub: 'バイリンガル字幕と学習コントロール',
        learnerBlurLabel: '翻訳をぼかす',
        learnerBlurSub: '翻訳をデフォルトでぼかす（ホバーまたはクリックで表示）',
        karaokeMode: 'カラオケモード',
        karaokeModeSub: '再生中の単語をアクセントカラーでハイライト表示',
        segmentMode: 'セグメントモード',
        segmentModeSub: '未再生テキストを非表示にせず薄く表示',
        enableAdvancedSearch: '詳細検索',
        enableAdvancedSearchSub: 'タグ、声優、サークル、時間でフィルタリング',
        enableWorkMetadata: '拡張メタデータ',
        enableWorkMetadataSub: '拡張メタデータと DLsite 情報を表示',
        enablePlayerTranslator: 'プレイヤー翻訳',
        enablePlayerTranslatorSub: 'プレイヤーインターフェースを翻訳',
        enableSupportButton: 'サポートボタン',
        enableSupportButtonSub: 'サポート/フィードバックリンクを表示',
        enableWorkTreeManager: 'フォルダナビ & フラット表示',
        enableWorkTreeManagerSub: '自動フォルダナビゲーションとフラット表示',
        enableTagFilters: 'タグフィルター',
        enableTagFiltersSub: '特定のタグを持つ作品を非表示',
        enableVectorSearch: 'セマンティック検索',
        enableVectorSearchSub: 'AI 駆動の検索——初回インデックスに約1日かかる場合があります',
        enableWhisper: 'Whisper',
        enableWhisperSub: 'ローカル AI 文字起こし',
        alwaysTranscribe: '自動文字起こし',
        alwaysTranscribeSub: '新しいトラック再生時に自動で文字起こしを開始',
        forceWhisperWasm: 'CPU モードを強制（WASM）',
        forceWhisperWasmSub: 'Whisper で WebGPU を無効化し、低スペック GPU でも安定するよう CPU 実行に切り替えます',
        enableFavicon: 'ダイナミックファビコン',
        enableFaviconSub: 'タブアイコンにカバーアートを表示',
        enableMediaSession: 'メディアセッション',
        enableMediaSessionSub: 'システムメディアコントロールのサポート',
        enableMenuIconFixer: 'メニューアイコン修正',
        enableMenuIconFixerSub: 'サイドバーの欠落アイコンを修正',
        enableStoreBackup: 'ストアバックアップ',
        enableStoreBackupSub: 'プラグインデータのバックアップ/復元',
        enableHVDBLink: 'HVDB リンク',
        enableHVDBLinkSub: 'HVDB メタデータへのリンク',
        enableInterfaceTranslator: 'インターフェース翻訳',
        enableInterfaceTranslatorSub: 'UI 要素を翻訳',
        enablePageTitleManager: 'ページタイトル管理',
        enablePageTitleManagerSub: 'タブタイトルの表示を修正',
        enableKeyboardManager: 'キーボードショートカット',
        enableKeyboardManagerSub: 'カスタムホットキー',
        enableRouteStateSync: 'ルート状態同期',
        enableRouteStateSyncSub: 'アプリの状態を URL と同期',
        enableMediaViewer: 'メディアビューア',
        enableMediaViewerSub: 'ライトボックスで画像/動画をプレビュー',
        enablePlayerFullscreen: 'フルスクリーンプレーヤー',
        enablePlayerFullscreenSub: '展開プレーヤーのフルスクリーン切替',
        enablePlayerGallery: 'プレーヤーギャラリー',
        enablePlayerGallerySub: 'プレーヤーのカバーアートで作品画像を閲覧',
        fullscreenToggle: 'フルスクリーン',
        fullscreenExit: 'フルスクリーン終了',
        galleryPrev: '前の画像',
        galleryNext: '次の画像',
        galleryExclude: 'この画像を非表示',
        gallerySlideshowPause: 'スライドショーを一時停止',
        gallerySlideshowResume: 'スライドショーを再開',
        galleryAutoSlideshow: '自動スライドショー',
        galleryAutoSlideshowSub: 'フルスクリーンとライトボックスで自動的に画像を切り替え',
        galleryAutoSlideshowInterval: 'スライドショー間隔',
        galleryAutoSlideshowIntervalSub: '画像切替間隔（秒）',
        keyboardShortcuts: 'キーボードショートカット',
        hotkeyPlayPause: '再生 / 一時停止',
        hotkeyMute: 'ミュート',
        hotkeyFullscreen: 'フルスクリーン',
        hotkeySeekBack: '巻き戻し (5秒)',
        hotkeySeekForward: '早送り (5秒)',
        hotkeySeekBackLong: '巻き戻し (10秒)',
        hotkeySeekForwardLong: '早送り (10秒)',
        hotkeyVolumeUp: '音量アップ',
        hotkeyVolumeDown: '音量ダウン',
        hotkeyPrevLine: '前の行 / トラック',
        hotkeyNextLine: '次の行 / トラック',
        hotkeyPrevTrack: '前のトラック',
        hotkeyNextTrack: '次のトラック',
        hotkeySpeedUp: '速度アップ',
        hotkeySpeedDown: '速度ダウン',
        hotkeyToggleBlur: 'ぼかし切替',
        revealTranslation: '翻訳を表示',
        hideTranslation: '翻訳を隠す',
        hotkeyToggleJP: '日本語切替',
        hotkeySpeedReset: '速度リセット',
        hotkeyGalleryExclude: '画像を非表示 (ギャラリー)',
        hotkeyGalleryPrev: 'ギャラリー前へ',
        hotkeyGalleryNext: 'ギャラリー次へ',
        hotkeyPressKey: 'キーを押してください…',
        hotkeyReset: 'デフォルトに戻す',
        enableWorkTreeCopy: 'コピーボタン',
        enableWorkTreeCopySub: 'ファイルエクスプローラーでファイル名をコピー',
        enableCommentSection: 'コメントセクション',
        enableCommentSectionSub: 'DLsite のレビューを表示',
        enableInfiniteScroll: '無限スクロール',
        enableInfiniteScrollSub: 'スクロール時に自動でコンテンツを読み込む',
        infScrollEndOfResults: '結果の最後です',
        infScrollRateLimitRetry: 'レート制限中。{seconds}秒後にリトライ...',
        infScrollRateLimitError: 'レート制限中。しばらくお待ちください。',
        infScrollLoadingImages: '{count} 枚の画像を読み込み中...',
        infScrollSales: '販売数: {count}',
        infScrollAllAges: '全年齢',

        // JOI Tool
        enableJoiTool: 'JOIツール',
        enableJoiToolSub: 'リアルタイム字幕と連動するインタラクティブエッジゲーム',
        alwaysShowJoi: 'JOIを常に表示',
        alwaysShowJoiSub: 'オーディオ再生時にJOIツールを自動的に有効化',
        joiTool: 'JOIツール',
        joiToggle: 'JOI切り替え',
        joiGo: 'GO',
        joiStop: 'ストップ',
        joiEdge: 'エッジ',
        joiCum: '射精',
        joiDenied: '拒否',
        joiRuined: '台無し',
        joiIdle: '準備完了',
        joiGoSlow: 'ゆっくり...',
        joiGoFast: '速く...',
        joiGoGentle: '優しく...',
        joiStopHands: '手を離して！',
        joiStopWait: '待って...',
        joiStopBreathe: '深呼吸...',
        joiEdgeClose: 'ギリギリ...',
        joiEdgeHold: 'そのまま...',
        joiEdgeDanger: '気をつけて...',
        joiCumNow: '今！',
        joiDeniedMsg: '今回はダメ。',
        joiRuinedMsg: '遅かった...',
        joiResuming: '{sec}秒後に再開...',
        joiNoWhisper: 'まずWhisperを有効にしてください',
        joiActivated: 'JOIが有効になりました',
        joiDeactivated: 'JOIが無効になりました',

        // Visualizer
        enableVisualizer: 'サウンドビジュアライザー',
        enableVisualizerSub: 'リアルタイム音声周波数ビジュアライザーバー',
        alwaysShowVisualizer: 'ビジュアライザーを常に表示',
        alwaysShowVisualizerSub: 'オーディオ再生時にビジュアライザーを自動的に有効化',
        vizToggle: 'ビジュアライザー切り替え',

        // Visit Counter
        enableVisitCounter: '訪問カウンター',
        enableVisitCounterSub: '各作品を開いた回数を表示',

        // Continue Listening
        enableContinueListening: '続きを聴く',
        enableContinueListeningSub: 'ホームに「聴いている」作品を表示',
        continueListeningTitle: '続きを聴く',

        // JPDB Integration
        jpdbSection: 'JPDB 連携',
        enableJpdb: 'JPDBを有効化',
        enableJpdbSub: 'jpdb.ioによるふりがな・アクセント・語彙管理',
        jpdbApiToken: 'APIトークン',
        jpdbApiTokenSub: '無料アカウントが必要 — jpdb.ioの設定ページからコピー',
        jpdbApiTokenPlaceholder: 'jpdb.io APIキーを貼り付け',
        jpdbGetApiKey: 'jpdb.ioでAPIキーを取得',
        jpdbShowFurigana: 'ふりがな表示',
        jpdbShowFuriganaSub: '漢字の上に読み仮名を表示',
        jpdbShowPitchAccent: 'アクセント表示',
        jpdbShowPitchAccentSub: '単語のピッチアクセントを表示（語彙ステータスの下線を上書き）',
        jpdbSiteFurigana: 'サイト全体のふりがな',
        jpdbSiteFuriganaSub: 'タイトル・タグ・ページ内容にふりがなを追加',
        jpdbSubtitleFurigana: '字幕のふりがな',
        jpdbSubtitleFuriganaSub: '学習モードの字幕にふりがなを追加',
        jpdbPitchStyle: 'アクセント表示形式',
        jpdbPitchStyleSub: 'ピッチアクセントの表示方法',
        jpdbPitchUnderline: '下線',
        jpdbPitchColor: '色',
        jpdbPitchBoth: '両方',
        jpdbPitchOff: 'オフ',
        hotkeyJpdbPopover: '単語ポップアップ',
        jpdbMiningDeck: 'マイニングデッキ',
        jpdbMiningDeckSub: '採掘した単語を追加するデッキ（空欄でFORQ）',
        jpdbMiningDeckPlaceholder: 'forq',
        jpdbAddToForq: 'FORQに追加',
        jpdbAddToForqSub: '採掘時にFORQデッキにも追加',
        jpdbDisableReviews: 'レビュー無効化',
        jpdbDisableReviewsSub: 'ポップアップのレビューボタンを非表示',
        jpdbUseTwoGrades: '2段階評価',
        jpdbUseTwoGradesSub: '5段階の代わりに不合格/合格を使用',
        jpdbNeverForgetDeck: '永久記憶デッキ',
        jpdbNeverForgetDeckSub: '永久記憶単語のデッキID',
        jpdbBlacklistDeck: 'ブラックリストデッキ',
        jpdbBlacklistDeckSub: 'ブラックリスト単語のデッキID',
        jpdbPopoverNoKey: 'jpdb.io APIキーを設定して語彙を管理',
        jpdbPopoverGetKey: 'APIキーを取得',
        jpdbPopoverRank: '頻度',
        jpdbPopoverState: '状態',
        jpdbBtnAdd: '追加',
        jpdbBtnNeverForget: '永久記憶',
        jpdbBtnForget: '記憶解除',
        jpdbBtnBlacklist: 'ブラックリスト',
        jpdbBtnUnlist: 'リスト解除',
        jpdbGradeNothing: '全く',
        jpdbGradeSomething: '少し',
        jpdbGradeHard: '難しい',
        jpdbGradeOkay: 'まあまあ',
        jpdbGradeEasy: '簡単',
        jpdbGradeFail: '不合格',
        jpdbGradePass: '合格',
        jpdbStateNew: '新規',
        jpdbStateLearning: '学習中',
        jpdbStateKnown: '既知',
        jpdbStateDue: '復習待ち',
        jpdbStateFailed: '失敗',
        jpdbStateLocked: 'ロック',
        jpdbStateNotInDeck: '未登録',
        jpdbStateSuspended: '一時停止',
        jpdbStateBlacklisted: 'ブラックリスト',
        jpdbStateNeverForget: '永久記憶',
        jpdbStateRedundant: '冗長',
        jpdbCredits: 'ふりがな・語彙機能はjpdb.ioを使用',
        jpdbCreditsReader: 'chinokusariのanki-jpdb.readerに基づく',
    },
};

export const I18n = {
    lang: (navigator.language.startsWith('zh') ? 'zh' : navigator.language.startsWith('ja') ? 'ja' : 'en') as SupportedLang,
    data: i18nData,

    /** Detect and sync language from the host Kikoeru app */
    syncFromHost(): void {
        // Priority 1: Kikoeru Vue app's $i18n locale (reads from the live Vue instance)
        try {
            const root = document.getElementById('q-app') as HTMLElement & { __vue__?: Record<string, unknown> } | null;
            const vueApp = root?.__vue__;
            const i18nLocale = (vueApp?.$i18n as Record<string, unknown> | undefined)?.locale as string | undefined;
            if (i18nLocale) {
                this.setLang(i18nLocale);
                return;
            }
        } catch {
            // Ignore if Vue app not accessible
        }

        // Priority 2: localStorage keys used by Kikoeru/asmr.one
        for (const key of ['locale', 'lang', 'language', 'i18n-locale']) {
            const stored = localStorage.getItem(key);
            if (stored) {
                this.setLang(stored);
                return;
            }
        }

        // Priority 3: navigator.language (browser locale - more reliable than <html lang>)
        if (navigator.language) {
            this.setLang(navigator.language);
            return;
        }

        // Priority 4: <html lang="..."> (often set to 'en' by default, least reliable)
        const htmlLang = document.documentElement.lang;
        if (htmlLang) {
            this.setLang(htmlLang);
            return;
        }
    },

    /** Set language from a locale string like 'en', 'zh-CN', 'ja', 'cn' */
    setLang(locale: string): void {
        const lower = locale.toLowerCase();
        if (lower.startsWith('zh') || lower === 'cn') {
            this.lang = 'zh';
        } else if (lower.startsWith('ja') || lower === 'jp') {
            this.lang = 'ja';
        } else {
            this.lang = 'en';
        }
    },

    t(key: string): string {
        return this.data[this.lang]?.[key] || this.data.en[key] || key;
    },

    format(key: string, params: Record<string, string | number>): string {
        let text = this.t(key);
        for (const [k, v] of Object.entries(params)) {
            text = text.replace(`{${k}}`, String(v));
        }
        return text;
    },
};


