EN_US = {
    "AGE": "Age",
    "GENRE": "Genre",
    "RELEASE_DATE": "Release date",
    "SERIES_NAME": "Series name",
    "PRODUCT_FORMAT": "Product format",
    "EVENT": "Event",
    "AUTHOR": "Author",
    "SCENARIO": "Scenario",
    "ILLUSTRATION": "Illustration",
    "MUSIC": "Music",
    "VOICE_ACTOR": "Voice Actor",
    "SUPPORTED_LANGUAGES": "Supported languages",
    "WORK_TYPE": "Work Type",
    "FILE_TYPE": "File Type",
    "CIRCLE": "Circle",
    "PLATFORM": "Platform",
    "PRICE": "Price",
    "RATING": "Rating",
    "LANGUAGES": "Languages",
    "AGE_RATING": "Age Rating",
    "DESCRIPTION": "Description",
    "CONTENT_SIZE": "Content Size",
    "TRIAL": "Trial Version",
    "COMPATIBLE": "Compatible With",
    "OPTIONS": "Options",
    "MACHINE": "Compatible Machines",
    "SEX_CATEGORY": "Gender Category",
    "WORK_CATEGORY": "Work Category",
    "KANA_NAME": "Work Name (Kana)"
}
