JA_JP = {
    # Existing translations
    "AGE": "年齢指定",
    "GENRE": "ジャンル",
    "RELEASE_DATE": "販売日",
    "SERIES_NAME": "シリーズ名",
    "PRODUCT_FORMAT": "作品形式",
    "EVENT": "イベント",
    "AUTHOR": "作者",
    "SCENARIO": "シナリオ",
    "ILLUSTRATION": "イラスト",
    "MUSIC": "音楽",
    "VOICE_ACTOR": "声優",
    "SUPPORTED_LANGUAGES": "対応言語",
    # New translations
    "WORK_TYPE": "作品タイプ",
    "FILE_TYPE": "ファイル形式",
    "CIRCLE": "サークル",
    "PLATFORM": "プラットフォーム",
    "PRICE": "価格",
    "RATING": "評価",
    "LANGUAGES": "対応言語",
    "AGE_RATING": "年齢指定",
    "DESCRIPTION": "説明",
    "CONTENT_SIZE": "容量",
    "TRIAL": "体験版",
    "COMPATIBLE": "動作環境",
    "OPTIONS": "オプション",
    "MACHINE": "対応機種",
    "SEX_CATEGORY": "性別指定",
    "WORK_CATEGORY": "作品カテゴリ",
    "KANA_NAME": "作品名(かな)"
}
