KO_KR = {
    "AGE": "연령 지정",
    "GENRE": "장르",
    "RELEASE_DATE": "판매일",
    "SERIES_NAME": "시리즈명",
    "PRODUCT_FORMAT": "작품 형식",
    "EVENT": "이벤트",
    "AUTHOR": "저자",
    "SCENARIO": "시나리오",
    "ILLUSTRATION": "일러스트",
    "MUSIC": "음악",
    "VOICE_ACTOR": "성우",
    "SUPPORTED_LANGUAGES": "지원 언어",
    "WORK_TYPE": "작품 유형",
    "FILE_TYPE": "파일 형식",
    "CIRCLE": "서클",
    "PLATFORM": "플랫폼",
    "PRICE": "가격",
    "RATING": "평가",
    "LANGUAGES": "지원 언어",
    "AGE_RATING": "연령 등급",
    "DESCRIPTION": "설명",
    "CONTENT_SIZE": "용량",
    "TRIAL": "체험판",
    "COMPATIBLE": "호환 환경",
    "OPTIONS": "옵션",
    "MACHINE": "대응 기종",
    "SEX_CATEGORY": "성별 분류",
    "WORK_CATEGORY": "작품 분류",
    "KANA_NAME": "작품명(가나)"
}
